CREATE TABLE ALC_STATS_IPRAN_HOUR (	
  FECHA                           DATE NOT NULL ENABLE, 
  MONITORED_OBJECT_POINTER        VARCHAR2(500 CHAR) NOT NULL ENABLE, 
  MONITORED_OBJECT_SITEID         VARCHAR2(50 CHAR) NOT NULL ENABLE, 
  MONITORED_OBJECT_SITE_NAME      VARCHAR2(50 CHAR) NOT NULL ENABLE, 
  DROP_EVENTS_PERIODIC            NUMBER NOT NULL ENABLE, 
  DROPPED_FRAMES_PERIODIC         NUMBER NOT NULL ENABLE, 
  RECEIVED_PACKETS_PERIODIC       NUMBER NOT NULL ENABLE, 
  TRANSMITTED_PACKETS_PERIODIC    NUMBER NOT NULL ENABLE, 
  RECEIVED_OCTETS_PERIODIC        NUMBER NOT NULL ENABLE, 
  TRANSMITTED_OCTETS_PERIODIC     NUMBER NOT NULL ENABLE, 
  RECEIVED_NON_UNI_PACK_PERIODIC  NUMBER NOT NULL ENABLE, 
  TRANS_NON_UNI_PACK_PERIODIC     NUMBER NOT NULL ENABLE, 
  RECEIVED_BAD_PACKETS_PERIODIC   NUMBER NOT NULL ENABLE, 
  TRANS_BAD_PACKETS_PERIODIC      NUMBER NOT NULL ENABLE, 
  INPUT_SPEED                     NUMBER NOT NULL ENABLE, 
  OUTPUT_SPEED                    NUMBER NOT NULL ENABLE, 
  IN_BANDWITH_UTIL                NUMBER NOT NULL ENABLE, 
  OUT_BANDWITH_UTIL               NUMBER NOT NULL ENABLE, 
  REC_OCTETS                      NUMBER NOT NULL ENABLE, 
  TRANS_OCTETS                    NUMBER NOT NULL ENABLE
)
NOCOMPRESS NOLOGGING
PARTITION BY RANGE (FECHA)
INTERVAL(NUMTODSINTERVAL(1, 'HOUR'))
(
  PARTITION ALCSTATSIPRANHOUR_FIRST VALUES LESS THAN (TO_DATE('2017-02-01 00:00:00','SYYYY-MM-DD HH24:MI:SS'))
)
TABLESPACE TBS_HOUR ;

COMMENT ON COLUMN ALC_STATS_IPRAN_HOUR.RECEIVED_NON_UNI_PACK_PERIODIC IS 'Reescritura de la columna receivedNonUnicastPacketsPeriodic por superar la cantidad de caracteres permitidos para nombrar un objeto';
COMMENT ON COLUMN ALC_STATS_IPRAN_HOUR.TRANS_NON_UNI_PACK_PERIODIC IS 'Reescritura de la columna transmittedNonUnicastPacketsPeriodic por superar la cantidad de caracteres permitidos para nombrar un objeto';
COMMENT ON COLUMN ALC_STATS_IPRAN_HOUR.TRANS_BAD_PACKETS_PERIODIC IS 'Reescritura de la columna transmittedBadPacketsPeriodic por superar la cantidad de caracteres permitidos para nombrar un objeto';
COMMENT ON TABLE ALC_STATS_IPRAN_HOUR  IS 'Se llena con datos de ALC_MEDIA_INDP_STATS_IPRAN_RAW';


CREATE INDEX IDX_ALC_STATS_IPRAN_HOUR_FMOS ON 
ALC_STATS_IPRAN_HOUR (FECHA,MONITORED_OBJECT_POINTER,MONITORED_OBJECT_SITEID,MONITORED_OBJECT_SITE_NAME) 
LOCAL TABLESPACE TBS_HOUR;

CREATE INDEX IDX_ALC_STATS_IPRAN_HOUR_F ON ALC_STATS_IPRAN_HOUR(TO_CHAR(FECHA,'DD.MM.YYYY')) LOCAL TABLESPACE TBS_HOUR;
CREATE INDEX IDX_ALC_STATS_IPRAN_HOUR_FH ON ALC_STATS_IPRAN_HOUR(TO_CHAR(FECHA,'DD.MM.YYYY HH24')) LOCAL TABLESPACE TBS_HOUR;