--
--
-- DROP TABLE ALC_PHYSICALPORT_IPRAN_OBJ PURGE;

CREATE TABLE ALC_PHYSICALPORT_IPRAN_OBJ (
  SPECIFIC_TYPE	              VARCHAR2(50 CHAR),
  DESCRIPTION	                VARCHAR2(255 CHAR),
  MODO	                      VARCHAR2(50 CHAR),
  MAC_ADDRESS	                VARCHAR2(50 CHAR),
  MTU_VALUE	                  VARCHAR2(50 CHAR),
  SPEED	                      VARCHAR2(50 CHAR),
  ACTUAL_SPEED	              VARCHAR2(50 CHAR),
  NUMBER_OF_POSSIBLE_CHANNELS NUMBER,
  SITE_ID	                    VARCHAR2(50 CHAR),
  SITE_NAME	                  VARCHAR2(50 CHAR),
  OPERATIONAL_STATE	          VARCHAR2(50 CHAR),
  ADMINISTRATIVE_STATE	      VARCHAR2(50 CHAR),
  OLC_STATE	                  VARCHAR2(255 CHAR),
  OBJECT_FULL_NAME	          VARCHAR2(500 CHAR),
  VALID_START_DATE            DATE  NOT NULL,
  VALID_FINISH_DATE           DATE DEFAULT '31.12.2999'
) NOCOMPRESS NOLOGGING
TABLESPACE TBS_AUXILIAR;

COMMENT ON COLUMN XML_MEDIA_INDEPEND_STATS.MODO IS 'Reescritura de la columna MODE por ser palabra reservada';
