

--
-- DROP TABLE ALC_LAGS_IPRAN_SCNIOLR_RAW PURGE;
--
create table ALC_LAGS_IPRAN_SCNIOLR_RAW (
  FECHA	                        DATE,
  PORT_ID	                      VARCHAR2(50 CHAR),
  QUEUE_ID	                    NUMBER,
  LAG_PORT	                    VARCHAR2(50 CHAR),
  TIME_RECORDED	                NUMBER,
  IN_PROFILE_OCTETS_FORWARDED	  NUMBER,
  IN_PROFILE_OCTETS_DROPPED	    NUMBER,
  OUT_OF_PROFILE_OCTETS_FWDED	  NUMBER,
  OUT_OF_PROFILE_OCTETS_DROPPED NUMBER,
  MONITORED_OBJECT_SITE_ID	    VARCHAR2(15 CHAR),
  MONITORED_OBJECT_SITE_NAME	  VARCHAR2(500 CHAR)
) NOCOMPRESS nologging
PARTITION BY RANGE (FECHA)
INTERVAL (NUMTODSINTERVAL (1,'HOUR'))
(
PARTITION LAGSIPRANSCNIOLRRAW_FIRST VALUES LESS THAN (TO_DATE('2017-02-01 00:00:00','SYYYY-MM-DD HH24:MI:SS')) 
)
TABLESPACE TBS_HOUR;

COMMENT ON TABLE ALC_LAGS_IPRAN_SCNIOLR_RAW IS 'Tabla para las mediciones serviceCombinedNetworkIngressOctetsLogRecord de la tabla XML_NTWQOS_1';

CREATE INDEX IDX_LAGS_IPRAN_SCNIOLR_RAW ON ALC_LAGS_IPRAN_SCNIOLR_RAW(FECHA,MONITORED_OBJECT_SITE_ID,MONITORED_OBJECT_SITE_NAME)
LOCAL TABLESPACE TBS_HOUR;

CREATE INDEX IDX_LAGSIPRANSCNIOLRRAW_F ON ALC_LAGS_IPRAN_SCNIOLR_RAW(TO_CHAR(FECHA,'DD.MM.YYYY'))
LOCAL TABLESPACE TBS_HOUR;

CREATE INDEX IDX_LAGSIPRANSCNIOLRRAW_FH ON ALC_LAGS_IPRAN_SCNIOLR_RAW(TO_CHAR(FECHA,'DD.MM.YYYY HH24'))
LOCAL TABLESPACE TBS_HOUR;
--
-- TYPE
--
CREATE OR REPLACE TYPE ALC_L_IPRAN_SCNIOLR_RAW_ROW AS OBJECT(
  FECHA	                        DATE,
  PORT_ID	                      VARCHAR2(50 CHAR),
  QUEUE_ID	                    NUMBER,
  LAG_PORT	                    VARCHAR2(50 CHAR),
  TIME_RECORDED	                NUMBER,
  IN_PROFILE_OCTETS_FORWARDED	  NUMBER,
  IN_PROFILE_OCTETS_DROPPED	    NUMBER,
  OUT_OF_PROFILE_OCTETS_FWDED	  NUMBER,
  OUT_OF_PROFILE_OCTETS_DROPPED NUMBER,
  MONITORED_OBJECT_SITE_ID	    VARCHAR2(15 CHAR),
  MONITORED_OBJECT_SITE_NAME	  VARCHAR2(500 CHAR)
);

CREATE OR REPLACE TYPE ALC_L_IPRAN_SCNIOLR_RAW_TY IS TABLE OF ALC_L_IPRAN_SCNIOLR_RAW_ROW;
