-- DROP TABLE ALC_IPRAN_LINKS PURGE;

CREATE TABLE ALC_IPRAN_LINKS (
  ELEMENT_ID        NUMBER, 
  ELEMENT_ALIASES   VARCHAR2(500 CHAR) NOT NULL ENABLE, 
  VALID_START_DATE  DATE, 
  VALID_FINISH_DATE DATE, 
  TIPO              VARCHAR2(40 CHAR),
  EQUIPO_A          VARCHAR2(50 CHAR) NOT NULL ENABLE,
  INTERFACE_A       VARCHAR2(50 CHAR) NOT NULL ENABLE,
  EQUIPO_B          VARCHAR2(50 CHAR) NOT NULL ENABLE,
  INTERFACE_B       VARCHAR2(50 CHAR) NOT NULL ENABLE,
  FLAG_ENABLED      CHAR(1 CHAR), 
  GRUPO             VARCHAR2(50 CHAR), 
  PAIS              VARCHAR2(20 CHAR), 
  ELEMENT_TYPE      VARCHAR2(20 CHAR), 
  ELEMENT_NAME      VARCHAR2(20 CHAR), 
  INTERFACE_NAME    VARCHAR2(500 CHAR), 
  GROUP_TYPE        VARCHAR2(20 CHAR), 
  ELEMENT_IP        VARCHAR2(15 CHAR), 
  NOMBRE_GRUPO      VARCHAR2(50 CHAR), 
  FRONTERA          VARCHAR2(30 CHAR), 
  SPEED_MODIFY      NUMBER
 ) NOCOMPRESS NOLOGGING
TABLESPACE TBS_AUXILIAR ;


ALTER TABLE ALC_IPRAN_LINKS ADD CONSTRAINT PK_ALC_IPRAN_LINKS PRIMARY KEY (ELEMENT_ALIASES);
---------------------------------------------------------------------------------------
-- SYNONYM
---------------------------------------------------------------------------------------
CREATE PUBLIC SYNONYM ALC_IPRAN_LINKS FOR SMART.ALC_IPRAN_LINKS;
---------------------------------------------------------------------------------------
-- PRIV.
---------------------------------------------------------------------------------------
GRANT SELECT,INSERT, UPDATE ON ALC_IPRAN_LINKS TO FRINALDI;
GRANT SELECT,INSERT, UPDATE ON ALC_IPRAN_LINKS TO MSTUYCK;
GRANT SELECT ON ALC_IPRAN_LINKS TO PRFC;