DROP TABLE ALC_STATS_CPUMEM_DAY PURGE;
--
CREATE TABLE ALC_STATS_CPUMEM_DAY(
  FECHA	                      DATE,
  MONITORED_OBJECT_SITE_ID	  VARCHAR2(50 CHAR),
  MONITORED_OBJECT_SITE_NAME	VARCHAR2(50 CHAR),
  SYSTEM_CPU_USAGE	          NUMBER,
  SYSTEM_CPU_USAGE_AVG	      NUMBER,
  SYSTEM_CPU_USAGE_MAX	      NUMBER,
  SYSTEM_MEMORY_USAGE	        NUMBER,
  SYSTEM_MEMORY_USAGE_AVG_MB	NUMBER,
  SYSTEM_MEMORY_USAGE_MAX_MB	NUMBER,
  SYSTEM_MEMORY_USAGE_AVG_PCT	NUMBER,
  SYSTEM_MEMORY_USAGE_MAX_PCT NUMBER,
  AVAILABLE_MEMORY	          NUMBER,
  AVAILABLE_MEMORY_AVG_MB	    NUMBER,
  AVAILABLE_MEMORY_MAX_MB	    NUMBER,
  AVAILABLE_MEMORY_AVG_PCT	  NUMBER,
  AVAILABLE_MEMORY_MAX_PCT	  NUMBER,
  ALLOCATED_MEMORY	          NUMBER,
  ALLOCATED_MEMORY_MB	        NUMBER
)NOLOGGING NOCOMPRESS
PARTITION BY RANGE (FECHA)
INTERVAL (NUMTODSINTERVAL(1,'DAY'))
(
PARTITION STATSCPUMEMDAY_FIRST VALUES LESS THAN (TO_DATE('2017-02-01','SYYYY-MM-DD'))
)
TABLESPACE TBS_DAY;

COMMENT ON TABLE ALC_STATS_CPUMEM_DAY IS 'Se llena con datos de las tablas ALC_STATS_CPUMEM_HOUR sumarizados a nivel DAY';
--