--------------------------------------------------------
--  DDL for Sequence ALC_IPRAN_LINKS_SEQ
--------------------------------------------------------

CREATE SEQUENCE ALC_IPRAN_LINKS_SEQ INCREMENT BY 1 START WITH 4000001 MAXVALUE 9999999999999999999999999999 NOCACHE;

CREATE PUBLIC SYNONYM ALC_IPRAN_LINKS_SEQ FOR SMART.ALC_IPRAN_LINKS_SEQ;

GRANT SELECT ON ALC_IPRAN_LINKS_SEQ TO PRFC;