
--
DROP TABLE ALC_SYSTEM_CPU_STATS_IPRAN_RAW PURGE;
--
CREATE TABLE ALC_SYSTEM_CPU_STATS_IPRAN_RAW(
  FECHA                       DATE NOT NULL,
  SYSTEM_CPU_USAGE	          NUMBER  DEFAULT 0 NOT NULL,
  TIME_CAPTURED	              NUMBER  DEFAULT 0 NOT NULL,
  PERIODIC_TIME	              NUMBER  DEFAULT 0 NOT NULL,
  MONITORED_OBJECT_SITE_ID    VARCHAR2(50 CHAR) NOT NULL,
  MONITORED_OBJECT_SITE_NAME  VARCHAR2(50 CHAR) NOT NULL
) NOCOMPRESS NOLOGGING
PARTITION BY RANGE (FECHA)
INTERVAL (NUMTODSINTERVAL (1,'HOUR'))
(
PARTITION SYSTEMCPUSTATSIPRANRAW_FIRST VALUES LESS THAN (TO_DATE('2017-02-01 00:00:00','SYYYY-MM-DD HH24:MI:SS')) 
)
TABLESPACE TBS_HOUR;

COMMENT ON TABLE ALC_SYSTEM_CPU_STATS_IPRAN_RAW IS 'Medición: Medicion de la CPU';

CREATE INDEX IDX_SYSTEMCPUSTATSIPRANRAW ON ALC_SYSTEM_CPU_STATS_IPRAN_RAW(FECHA,MONITORED_OBJECT_SITE_ID,MONITORED_OBJECT_SITE_NAME)
LOCAL TABLESPACE TBS_HOUR;

CREATE INDEX IDX_SYSTEMCPUSTATSIPRANRAW_F ON ALC_SYSTEM_CPU_STATS_IPRAN_RAW(TO_CHAR(FECHA,'DD.MM.YYYY')) LOCAL TABLESPACE TBS_HOUR;

CREATE INDEX IDX_SYSTEMCPUSTATSIPRANRAW_FH ON ALC_SYSTEM_CPU_STATS_IPRAN_RAW(TO_CHAR(FECHA,'DD.MM.YYYY HH24')) LOCAL TABLESPACE TBS_HOUR;
--
-- TYPE
-- DROP TYPE ALC_S_C_S_IPRAN_ROW;

CREATE OR REPLACE TYPE ALC_S_C_S_IPRAN_ROW AS OBJECT(
  FECHA	                      DATE,
  SYSTEM_CPU_USAGE	          NUMBER,
  TIME_CAPTURED	              NUMBER,
  PERIODIC_TIME	              NUMBER,
  MONITORED_OBJECT_SITE_ID	  VARCHAR2(15 CHAR),
  MONITORED_OBJECT_SITE_NAME	VARCHAR2(50 CHAR)
);
-- DROP TYPE ALC_S_C_S_IPRAN_TY;
CREATE OR REPLACE TYPE ALC_S_C_S_IPRAN_TY IS TABLE OF ALC_S_C_S_IPRAN_ROW;       