

create or replace TYPE ALC_L_IPRAN_SCNIOLR_RAW_ROW AS OBJECT(
  FECHA	                        DATE,
  PORT_ID	                      VARCHAR2(50 CHAR),
  QUEUE_ID	                    NUMBER,
  LAG_PORT	                    VARCHAR2(50 CHAR),
  TIME_RECORDED	                NUMBER,
  IN_PROFILE_OCTETS_FORWARDED	  NUMBER,
  IN_PROFILE_OCTETS_DROPPED	    NUMBER,
  OUT_OF_PROFILE_OCTETS_FWDED	  NUMBER,
  OUT_OF_PROFILE_OCTETS_DROPPED NUMBER,
  MONITORED_OBJECT_SITE_ID	    VARCHAR2(15 CHAR),
  MONITORED_OBJECT_SITE_NAME	  VARCHAR2(500 CHAR)
);
--
create or replace TYPE ALC_L_IPRAN_SCNIOLR_RAW_TY IS TABLE OF ALC_L_IPRAN_SCNIOLR_RAW_ROW;
--
create or replace TYPE ALC_M_I_S_IPRAN_RAW_ROW AS OBJECT (
FECHA	DATE,
DROP_EVENTS_PERIODIC	NUMBER,
DROPPED_FRAMES_PERIODIC	NUMBER,
RECEIVED_PACKETS_PERIODIC	NUMBER,
TRANSMITTED_PACKETS_PERIODIC	NUMBER,
RECEIVED_OCTETS_PERIODIC	NUMBER,
TRANSMITTED_OCTETS_PERIODIC	NUMBER,
REC_NON_UNICAST_PAC_PERIODIC	NUMBER,
TRAN_NON_UNICAST_PAC_PERIODIC	NUMBER,
RECEIVED_BAD_PACKETS_PERIODIC	NUMBER,
TRAN_BAD_PACKETS_PERIODIC	NUMBER,
INPUT_SPEED	NUMBER,
OUTPUT_SPEED	NUMBER,
DUPLEX	VARCHAR2(50 CHAR),
DUPLEX_CHANGESPERIODIC	NUMBER,
TIME_CAPTURED	NUMBER,
PERIODIC_TIME	NUMBER,
MONITORED_OBJECT_POINTER	VARCHAR2(500 CHAR),
MONITORED_OBJECT_SITE_ID	VARCHAR2(50 CHAR),
MONITORED_OBJECT_SITENAME	VARCHAR2(50 CHAR),
IN_BANDWITH_UTIL	NUMBER,
OUT_BANDWITH_UTIL	NUMBER,
REC_OCTETS	NUMBER,
TRANS_OCTETS	NUMBER
);
--
create or replace TYPE ALC_M_I_S_IPRAN_RAW_TY IS TABLE OF ALC_M_I_S_IPRAN_RAW_ROW;
--
create or replace TYPE ALC_S_C_S_IPRAN_ROW AS OBJECT(
  FECHA	                      DATE,
  SYSTEM_CPU_USAGE	          NUMBER,
  TIME_CAPTURED	              NUMBER,
  PERIODIC_TIME	              NUMBER,
  MONITORED_OBJECT_SITE_ID	  VARCHAR2(15 CHAR),
  MONITORED_OBJECT_SITE_NAME	VARCHAR2(50 CHAR)
);
--
create or replace TYPE ALC_S_C_S_IPRAN_TY IS TABLE OF ALC_S_C_S_IPRAN_ROW;
--
create or replace TYPE ALC_S_M_S_IPRAN_RAW_ROW AS OBJECT(
  FECHA                       DATE,
  SYSTEM_MEMORY_USAGE	        NUMBER,
  SMS_TIME_CAPTURED		        NUMBER,
  SMS_PERIODIC_TIME		        NUMBER,
  MONITORED_OBJECT_SITE_ID	  VARCHAR2(50 CHAR),
  MONITORED_OBJECT_SITE_NAME	VARCHAR2(50 CHAR),
  SMS_SYSTEM_MEMORY_USAGE_MB  NUMBER,
  SMS_SYSTEM_MEMORY_USAGE_AVG NUMBER,
  AVAILABLE_MEMORY		        NUMBER,
  AVMS_TIME_CAPTURED		      NUMBER,
  AVMS_PERIODIC_TIME		      NUMBER,
  AVMS_AVAILABLE_MEMORY_PCT   NUMBER,
  AVMS_AVAILABLE_MEMORY_MB    NUMBER,
  ALLOCATED_MEMORY		        NUMBER,
  AMS_TIME_CAPTURED		        NUMBER,
  AMS_PERIODIC_TIME		        NUMBER,
  AMS_ALLOCATED_MEMORY_MB     NUMBER
);
--
create or replace TYPE ALC_S_M_S_IPRAN_RAW_TY IS TABLE OF ALC_S_M_S_IPRAN_RAW_ROW;