
--DROP TABLE ALC_STATS_CPUMEM_IBHW PURGE;

CREATE TABLE ALC_STATS_CPUMEM_IBHW(
  FECHA	                      DATE,
  MONITORED_OBJECT_SITE_ID	  VARCHAR2(50 CHAR),
  MONITORED_OBJECT_SITE_NAME	VARCHAR2(50 CHAR),
  SYSTEM_CPU_USAGE	          NUMBER,
  SYSTEM_CPU_USAGE_AVG	      NUMBER,
  SYSTEM_CPU_USAGE_MAX	      NUMBER,
  SYSTEM_MEMORY_USAGE	        NUMBER,
  SYSTEM_MEMORY_USAGE_AVG_MB	NUMBER,
  SYSTEM_MEMORY_USAGE_MAX_MB	NUMBER,
  SYSTEM_MEMORY_USAGE_AVG_PCT	NUMBER,
  SYSTEM_MEMORY_USAGE_MAX_PCT NUMBER,
  AVAILABLE_MEMORY	          NUMBER,
  AVAILABLE_MEMORY_AVG_MB	    NUMBER,
  AVAILABLE_MEMORY_MAX_MB	    NUMBER,
  AVAILABLE_MEMORY_AVG_PCT	  NUMBER,
  AVAILABLE_MEMORY_MAX_PCT	  NUMBER,
  ALLOCATED_MEMORY	          NUMBER,
  ALLOCATED_MEMORY_MB	        NUMBER
)NOLOGGING NOCOMPRESS
PARTITION BY RANGE (FECHA) INTERVAL (NUMTODSINTERVAL(1, 'DAY')) 
(
PARTITION STATSCPUMEMIBHW_FIRST  VALUES LESS THAN (TO_DATE(' 2016-10-01','SYYYY-MM-DD'))
)
TABLESPACE TBS_SUMMARY;

COMMENT ON TABLE ALC_STATS_CPUMEM_IBHW IS 'Se llena con datos de las tablas ALC_STATS_CPUMEM_BH sumarizados a nivel IBHW';

CREATE INDEX IDX_ALC_STATS_CPUMEM_IBHW ON ALC_STATS_CPUMEM_IBHW (FECHA,MONITORED_OBJECT_SITE_ID,MONITORED_OBJECT_SITE_NAME) 
LOCAL TABLESPACE TBS_SUMMARY;

CREATE INDEX IDX_ALC_STATS_CPUMEM_IBHW_F ON ALC_STATS_CPUMEM_IBHW (TO_CHAR(FECHA,'DD.MM.YYYY')) 
LOCAL TABLESPACE TBS_SUMMARY;