
--
-- DROP TABLE ALC_SYSTEM_MEM_STATS_IPRAN_RAW;
--
CREATE TABLE ALC_SYSTEM_MEM_STATS_IPRAN_RAW(
  FECHA                       DATE,
  SYSTEM_MEMORY_USAGE	        NUMBER,
  SMS_TIME_CAPTURED		        NUMBER,
  SMS_PERIODIC_TIME		        NUMBER,
  MONITORED_OBJECT_SITE_ID	  VARCHAR2(50 CHAR) NOT NULL,
  MONITORED_OBJECT_SITE_NAME	VARCHAR2(50 CHAR) NOT NULL,
  SMS_SYSTEM_MEMORY_USAGE_MB  NUMBER,
  SMS_SYSTEM_MEMORY_USAGE_AVG NUMBER,
  AVAILABLE_MEMORY		        NUMBER,
  AVMS_TIME_CAPTURED		      NUMBER,
  AVMS_PERIODIC_TIME		      NUMBER,
  AVMS_AVAILABLE_MEMORY_PCT   NUMBER,
  AVMS_AVAILABLE_MEMORY_MB    NUMBER,
  ALLOCATED_MEMORY		        NUMBER,
  AMS_TIME_CAPTURED		        NUMBER,
  AMS_PERIODIC_TIME		        NUMBER,
  AMS_ALLOCATED_MEMORY_MB     NUMBER
) NOCOMPRESS NOLOGGING
PARTITION BY RANGE (FECHA)
INTERVAL (NUMTODSINTERVAL (1,'HOUR'))
(
PARTITION SYSTEMMEMSTATSIPRANRAW_FIRST VALUES LESS THAN (TO_DATE('2017-02-01 00:00:00','SYYYY-MM-DD HH24:MI:SS')) 
)
TABLESPACE TBS_HOUR;

COMMENT ON TABLE ALC_SYSTEM_MEM_STATS_IPRAN_RAW IS'Medición: Medicion de la Memoria';
COMMENT ON COLUMN ALC_SYSTEM_MEM_STATS_IPRAN_RAW.SYSTEM_MEMORY_USAGE	        IS 'Viene en el XML	equipment.SystemMemoryStats (SMS)';
COMMENT ON COLUMN ALC_SYSTEM_MEM_STATS_IPRAN_RAW.SMS_TIME_CAPTURED		        IS 'Viene en el XML	equipment.SystemMemoryStats';
COMMENT ON COLUMN ALC_SYSTEM_MEM_STATS_IPRAN_RAW.SMS_PERIODIC_TIME			      IS 'Viene en el XML	equipment.SystemMemoryStats';
COMMENT ON COLUMN ALC_SYSTEM_MEM_STATS_IPRAN_RAW.MONITORED_OBJECT_SITE_ID		  IS 'Viene en el XML	equipment.SystemMemoryStats';
COMMENT ON COLUMN ALC_SYSTEM_MEM_STATS_IPRAN_RAW.MONITORED_OBJECT_SITE_NAME		IS 'Viene en el XML	equipment.SystemMemoryStats';
COMMENT ON COLUMN ALC_SYSTEM_MEM_STATS_IPRAN_RAW.SMS_SYSTEM_MEMORY_USAGE_MB   IS 'Se calcula --> sms_system_Memory_Usage/1048576';
COMMENT ON COLUMN ALC_SYSTEM_MEM_STATS_IPRAN_RAW.SMS_SYSTEM_MEMORY_USAGE_AVG  IS 'Se calcula --> sms_system_Memory_Usage/(sms_available_Memory+sms_allocated_Memory)) (%)';	
COMMENT ON COLUMN ALC_SYSTEM_MEM_STATS_IPRAN_RAW.AVAILABLE_MEMORY		        	IS 'Viene en el XML	equipment.AvailableMemoryStats (AVMS)';
COMMENT ON COLUMN ALC_SYSTEM_MEM_STATS_IPRAN_RAW.AVMS_TIME_CAPTURED		        IS 'Viene en el XML	equipment.AvailableMemoryStats';
COMMENT ON COLUMN ALC_SYSTEM_MEM_STATS_IPRAN_RAW.AVMS_PERIODIC_TIME		        IS 'Viene en el XML	equipment.AvailableMemoryStats';
COMMENT ON COLUMN ALC_SYSTEM_MEM_STATS_IPRAN_RAW.AVMS_AVAILABLE_MEMORY_PCT    IS 'Se calcula --> AVMS_available_Memory/(AVMS_available_Memory+AVMS_allocated_Memory)) (%)';
COMMENT ON COLUMN ALC_SYSTEM_MEM_STATS_IPRAN_RAW.AVMS_AVAILABLE_MEMORY_MB     IS 'Se calcula --> AVMS_available_Memory/1048576) (MB)';
COMMENT ON COLUMN ALC_SYSTEM_MEM_STATS_IPRAN_RAW.ALLOCATED_MEMORY		        	IS 'Viene en el XML	equipment.AllocatedMemoryStats (AMS)';
COMMENT ON COLUMN ALC_SYSTEM_MEM_STATS_IPRAN_RAW.AMS_TIME_CAPTURED		        IS 'Viene en el XML	equipment.AllocatedMemoryStats';
COMMENT ON COLUMN ALC_SYSTEM_MEM_STATS_IPRAN_RAW.AMS_PERIODIC_TIME		        IS 'Viene en el XML	equipment.AllocatedMemoryStats';
COMMENT ON COLUMN ALC_SYSTEM_MEM_STATS_IPRAN_RAW.AMS_ALLOCATED_MEMORY_MB      IS 'Se calcula --> AMS_allocated_Memory/1048576) (MB)';

CREATE INDEX IDX_SYSTEMMEMSTATSIPRANRAW ON ALC_SYSTEM_MEM_STATS_IPRAN_RAW(FECHA,MONITORED_OBJECT_SITE_ID,MONITORED_OBJECT_SITE_NAME)
LOCAL TABLESPACE TBS_HOUR;

CREATE INDEX IDX_SYSTEMMEMSTATSIPRANRAW_F ON ALC_SYSTEM_MEM_STATS_IPRAN_RAW(TO_CHAR(FECHA,'DD.MM.YYYY'))
LOCAL TABLESPACE TBS_HOUR;

CREATE INDEX IDX_SYSTEMMEMSTATSIPRANRAW_FH ON ALC_SYSTEM_MEM_STATS_IPRAN_RAW(TO_CHAR(FECHA,'DD.MM.YYYY HH24'))
LOCAL TABLESPACE TBS_HOUR;
--
-- TYPE
-- DROP TYPE ALC_S_M_S_IPRAN_RAW_ROW;

CREATE OR REPLACE TYPE ALC_S_M_S_IPRAN_RAW_ROW AS OBJECT(
  FECHA                       DATE,
  SYSTEM_MEMORY_USAGE	        NUMBER,
  SMS_TIME_CAPTURED		        NUMBER,
  SMS_PERIODIC_TIME		        NUMBER,
  MONITORED_OBJECT_SITE_ID	  VARCHAR2(50 CHAR),
  MONITORED_OBJECT_SITE_NAME	VARCHAR2(50 CHAR),
  SMS_SYSTEM_MEMORY_USAGE_MB  NUMBER,
  SMS_SYSTEM_MEMORY_USAGE_AVG NUMBER,
  AVAILABLE_MEMORY		        NUMBER,
  AVMS_TIME_CAPTURED		      NUMBER,
  AVMS_PERIODIC_TIME		      NUMBER,
  AVMS_AVAILABLE_MEMORY_PCT   NUMBER,
  AVMS_AVAILABLE_MEMORY_MB    NUMBER,
  ALLOCATED_MEMORY		        NUMBER,
  AMS_TIME_CAPTURED		        NUMBER,
  AMS_PERIODIC_TIME		        NUMBER,
  AMS_ALLOCATED_MEMORY_MB     NUMBER
);
-- DROP TYPE ALC_S_M_S_IPRAN_RAW_TY;
CREATE OR REPLACE TYPE ALC_S_M_S_IPRAN_RAW_TY IS TABLE OF ALC_S_M_S_IPRAN_RAW_ROW;
