--
--DROP TABLE ALC_STATS_IPRAN_IBHW PURGE;

CREATE TABLE ALC_STATS_IPRAN_IBHW(
  FECHA	                          DATE,
  MONITORED_OBJECT_POINTER	      VARCHAR2(500 CHAR),
  MONITORED_OBJECT_SITEID	        VARCHAR2(50 CHAR),
  MONITORED_OBJECT_SITE_NAME	    VARCHAR2(50 CHAR),
  DROP_EVENTS_PERIODIC	          NUMBER,
  DROPPED_FRAMES_PERIODIC	        NUMBER,
  RECEIVED_PACKETS_PERIODIC	      NUMBER,
  TRANSMITTED_PACKETS_PERIODIC	  NUMBER,
  RECEIVED_OCTETS_PERIODIC	      NUMBER,
  TRANSMITTED_OCTETS_PERIODIC	    NUMBER,
  RECEIVED_NON_UNI_PACK_PERIODIC  NUMBER,
  TRANS_NON_UNI_PACK_PERIODIC	    NUMBER,
  RECEIVED_BAD_PACKETS_PERIODIC	  NUMBER,
  TRANS_BAD_PACKETS_PERIODIC	    NUMBER,
  INPUT_SPEED	                    NUMBER,
  OUTPUT_SPEED	                  NUMBER,
  IN_BANDWITH_UTIL	              NUMBER,
  OUT_BANDWITH_UTIL	              NUMBER,
  REC_OCTETS	                    NUMBER,
  TRANS_OCTETS	                  NUMBER
) NOLOGGING NOCOMPRESS
PARTITION BY RANGE (FECHA)
INTERVAL(NUMTODSINTERVAL(1, 'DAY'))
(
  PARTITION ALCSTATSIPRANIBHW_FIRST VALUES LESS THAN (TO_DATE('2017-02-01 00:00:00','SYYYY-MM-DD HH24:MI:SS'))
)
TABLESPACE TBS_SUMMARY;


CREATE INDEX IDX_ALC_STATS_IPRAN_IBHW_FMOS ON 
ALC_STATS_IPRAN_IBHW (FECHA,MONITORED_OBJECT_POINTER,MONITORED_OBJECT_SITEID,MONITORED_OBJECT_SITE_NAME) 
LOCAL TABLESPACE TBS_SUMMARY;

CREATE INDEX IDX_ALC_STATS_IPRAN_IBHW_F ON ALC_STATS_IPRAN_IBHW (TO_CHAR(FECHA,'DD.MM.YYYY')) LOCAL TABLESPACE TBS_SUMMARY;

CREATE INDEX IDX_ALC_STATS_IPRAN_IBHW_FH ON ALC_STATS_IPRAN_IBHW (TO_CHAR(FECHA,'DD.MM.YYYY HH24')) LOCAL TABLESPACE TBS_SUMMARY;

COMMENT ON TABLE ALC_STATS_IPRAN_IBHW IS 'Contiene los datos de la tabla ALC_STATS_IPRAN_BH sumarizados a nivel IBHW';