
create or replace PACKAGE G_ALC_IPRAN AS 
  /**
  * Author: Carrasco Marcelo mailto: mcarrasco@harriague.com
  * Date: 01/12/2016
  * Comment: Paquete para conter la funcionalidad asociada a NOKIA ALU IPRAN.
  */
  -- BULK COLLECT LIMIT
  bulk_limit  CONSTANT PLS_INTEGER := 100;
  -- LIMITE DE FILAS PARA LA SUMARIZACION IBHW
  limit_in    CONSTANT PLS_INTEGER  := 3; 
  -- PIPELINED FUNCTIONS
  FUNCTION GET_XML_M_I_STATS_1_DATA(P_FECHAHORA IN VARCHAR2) RETURN ALC_M_I_S_IPRAN_RAW_TY PIPELINED;
  FUNCTION GET_XML_SYSTEM_STATS_3_DATA(P_FECHAHORA IN VARCHAR2) RETURN ALC_S_C_S_IPRAN_TY PIPELINED;
  FUNCTION GET_XML_SYSTEM_STATS_1_2_DATA(P_FECHAHORA  IN VARCHAR2) RETURN ALC_S_M_S_IPRAN_RAW_TY PIPELINED;
  FUNCTION GET_XML_NTWQOS_DATA(P_FECHAHORA IN VARCHAR2) RETURN ALC_L_IPRAN_SCNEOLR_RAW_TY PIPELINED;
  FUNCTION GET_XML_NTWQOS_1_DATA(P_FECHAHORA IN VARCHAR2) RETURN ALC_L_IPRAN_SCNIOLR_RAW_TY PIPELINED;
  
  -- PROCEDURES
  /**
  * Insert los datos de la tabla XML_CARD_STATUS en la tabla ALC_CARDSLOT_IPRAN_OBJ
  */
  PROCEDURE INS_ALC_CARDSLOT_IPRAN_OBJ(P_FECHA IN VARCHAR2);
  /**
  * Insert los datos de la tabla XML_MEDIA_INDP_STATS en la tabla ALC_PHYSICALPORT_IPRAN_OBJ
  */
  PROCEDURE INS_ALC_PHYSICALPORT_IPRAN_OBJ(P_FECHA IN VARCHAR2);
  /**
  * Inserta los datos de la tabla XML_MEDIA_INDEPEND_STATS_1 en la tabla ALC_MEDIA_INDP_STATS_IPRAN_RAW
  */
  PROCEDURE INS_ALC_M_I_S_IPRAN_RAW(P_FECHAHORA IN VARCHAR2);
  /**
  * Inserta los datos de la tabla XML_SYSTEM_STATS_3 en la tabla ALC_SYTEM_CPU_STATS_IPRAN_RAW
  */
  PROCEDURE INS_ALC_S_C_S_IPRAN_RAW(P_FECHAHORA IN VARCHAR2);
  /**
  * Inserta los datos de laS tabla XML_SYSTEM_STATS, XML_SYSTEM_STATS_1, XML_SYSTEM_STATS_2 en la tabla ALC_SYTEM_MEM_STATS_IPRAN_RAW
  */
  PROCEDURE INS_ALC_S_M_S_IPRAN_RAW(P_FECHAHORA IN VARCHAR2);
  /**
  * Inserta los datos de laS tabla XML_NTWQOS en la tabla ALC_LAGS_IPRAN_SCNEOLR_RAW
  */
  PROCEDURE INS_ALC_L_I_SCNEOLR_RAW(P_FECHAHORA IN VARCHAR2);
  /**
  * Inserta los datos de laS tabla XML_NTWQOS_1 en la tabla ALC_LAGS_IPRAN_SCNIOLR_RAW
  */
  PROCEDURE INS_ALC_L_I_SCNIOLR_RAW(P_FECHAHORA IN VARCHAR2);
  /**
  * Inserta los datos de la ALC_MEDIA_INDP_STATS_IPRAN_RAW sumarizados a nivel HOUR en la tabla ALC_STATS_IPRAN_HOUR
  * Param: P_FECHAHORA --> DD.MM.YYYY HH24
  */
  PROCEDURE INS_ALC_STATS_IPRAN_HOUR(P_FECHAHORA IN VARCHAR2);
  /**
  * Inserta los datos de la ALC_STATS_IPRAN_HOUR sumarizados a nivel DAY en la tabla ALC_STATS_IPRAN_DAY
  */
  PROCEDURE INS_ALC_STATS_IPRAN_DAY(P_FECHA IN VARCHAR2);
  /**
  * Inserta los datos de la ALC_STATS_IPRAN_HOUR sumarizados a nivel BH en la tabla ALC_STATS_IPRAN_BH
  */
  PROCEDURE INS_ALC_STATS_IPRAN_BH(P_FECHA IN VARCHAR2);
  /**
  * Inserta los datos de la ALC_STATS_IPRAN_BH sumarizados a nivel IBHW en la tabla ALC_STATS_IPRAN_IBHW
  */
  PROCEDURE INS_ALC_STATS_IPRAN_IBHW(P_FECHA_DOMINGO IN VARCHAR2,P_FECHA_SABADO IN VARCHAR2);
  /**
  * Inserta los datos de laS ALC_SYSTEM_CPU_STATS_IPRAN_RAW y ALC_SYSTEM_MEM_STATS_IPRAN_RAW sumarizados a nivel HOUR en
  * la tabla  ALC_STATS_CPUMEM_HOUR
  * Param: P_FECHAHORA --> DD.MM.YYYY HH24
  */
  PROCEDURE INS_ALC_STATS_CPUMEM_HOUR(P_FECHAHORA IN VARCHAR2);
  /**
  * Inserta los datos de la tabla ALC_STATS_CPUMEM_HOUR sumarizados  a nivel DAY en la tabla ALC_STATS_CPUMEM_DAY
  */
  PROCEDURE INS_ALC_STATS_CPUMEM_DAY(P_FECHA IN VARCHAR2);
  /**
  * Inserta los datos de la tabla ALC_STATS_CPUMEM_HOUR sumarizados  a nivel BH en la tabla ALC_STATS_CPUMEM_BH
  */
  PROCEDURE INS_ALC_STATS_CPUMEM_BH(P_FECHA IN VARCHAR2);
  /**
  * Inserta los datos de la tabla ALC_STATS_CPUMEM_BH sumarizados  a nivel IBHW en la tabla ALC_STATS_CPUMEM_IBHW
  */
  PROCEDURE INS_ALC_STATS_CPUMEM_IBHW(P_FECHA_DOMINGO IN VARCHAR2,P_FECHA_SABADO IN VARCHAR2);
  /**
  * Ejecuta los procedimientos de calculo de sumarizaciones en los distintos niveles. Si es DOMINGO, ejecuta el calculo
  * de IBHW.
  */
  PROCEDURE ALC_CALC_SUM_DAY_BH_IBHW(P_FECHA IN  VARCHAR2);
END G_ALC_IPRAN;