
SELECT LENGTH('monitored_Object_Site_Name') FROM DUAL;

CREATE TABLE ALC_SYSTEM_MEM_STATS_IPRAN_AUX(
SMS_SYSTEM_MEMORY_USAGE	        NUMBER NOT NULL,
SMS_TIME_CAPTURED		            NUMBER NOT NULL,
SMS_PERIODIC_TIME		            NUMBER NOT NULL,
SMS_MONITORED_OBJECT_SITE_ID	  VARCHAR2(50 CHAR) NOT NULL,
SMS_MONITORED_OBJECT_SITE_NAME	VARCHAR2(50 CHAR) NOT NULL,
SMS_SYSTEM_MEMORY_USAGE_MB      NUMBER GENERATED ALWAYS AS (SMS_SYSTEM_MEMORY_USAGE/1048576),
SMS_SYSTEM_MEMORY_USAGE_AVG     NUMBER GENERATED ALWAYS AS (SMS_SYSTEM_MEMORY_USAGE/(SMS_AVAILABLE_MEMORY+SMS_ALLOCATED_MEMORY)),
AVMS_AVAILABLE_MEMORY		        NUMBER NOT NULL,
AVMS_TIME_CAPTURED		          NUMBER NOT NULL,
AVMS_PERIODIC_TIME		          NUMBER NOT NULL,
AVMS_MONITORED_OBJECT_SITE_ID	  VARCHAR2(50 CHAR) NOT NULL,
AVMS_MONITORED_OBJECT_SITE_NAME	VARCHAR2(50 CHAR) NOT NULL,
AVMS_AVAILABLE_MEMORY_PCT       NUMBER GENERATED ALWAYS AS (AVMS_AVAILABLE_MEMORY/(AVMS_AVAILABLE_MEMORY+AVMS_ALLOCATED_MEMORY)),
AVMS_AVAILABLE_MEMORY_MB        NUMBER GENERATED ALWAYS AS (AVMS_AVAILABLE_MEMORY/1048576),
AMS_ALLOCATED_MEMORY		        NUMBER NOT NULL,
AMS_TIME_CAPTURED		            NUMBER NOT NULL,
AMS_PERIODIC_TIME		            NUMBER NOT NULL,
AMS_MONITORED_OBJECT_SITE_ID	  VARCHAR2(50 CHAR) NOT NULL,
AMS_MONITORED_OBJECT_SITE_NAME	VARCHAR2(50 CHAR) NOT NULL,
AMS_ALLOCATED_MEMORY_MB         NUMBER GENERATED ALWAYS AS (AMS_ALLOCATED_MEMORY/1048576)
) NOCOMPRESS NOLOGGING;
-- TABLESPACE TBS_AUXILIAR;

COMMENT ON TABLE ALC_SYSTEM_MEM_STATS_IPRAN_AUX IS'Tabla auxiliar para el calculo automatico de las col. que contienen formulas';

COMMENT ON TABLE ALC_SYSTEM_MEM_STATS_IPRAN_AUX.SMS_SYSTEM_MEMORY_USAGE	          IS 'Viene en el XML	equipment.SystemMemoryStats (SMS)';
COMMENT ON TABLE ALC_SYSTEM_MEM_STATS_IPRAN_AUX.SMS_TIME_CAPTURED		              IS 'Viene en el XML	equipment.SystemMemoryStats';
COMMENT ON TABLE ALC_SYSTEM_MEM_STATS_IPRAN_AUX.SMS_PERIODIC_TIME			            IS 'Viene en el XML	equipment.SystemMemoryStats';
COMMENT ON TABLE ALC_SYSTEM_MEM_STATS_IPRAN_AUX.SMS_MONITORED_OBJECT_SITE_ID		  IS 'Viene en el XML	equipment.SystemMemoryStats';
COMMENT ON TABLE ALC_SYSTEM_MEM_STATS_IPRAN_AUX.SMS_MONITORED_OBJECT_SITE_NAME		IS 'Viene en el XML	equipment.SystemMemoryStats';
COMMENT ON TABLE ALC_SYSTEM_MEM_STATS_IPRAN_AUX.SMS_SYSTEM_MEMORY_USAGE_MB       	IS 'Se calcula --> sms_system_Memory_Usage/1048576';
COMMENT ON TABLE ALC_SYSTEM_MEM_STATS_IPRAN_AUX.SMS_SYSTEM_MEMORY_USAGE_AVG      	IS 'Se calcula --> sms_system_Memory_Usage/(sms_available_Memory+sms_allocated_Memory)) (%)';	
COMMENT ON TABLE ALC_SYSTEM_MEM_STATS_IPRAN_AUX.AVMS_AVAILABLE_MEMORY		        	IS 'Viene en el XML	equipment.AvailableMemoryStats (AVMS)';
COMMENT ON TABLE ALC_SYSTEM_MEM_STATS_IPRAN_AUX.AVMS_TIME_CAPTURED		          	IS 'Viene en el XML	equipment.AvailableMemoryStats';
COMMENT ON TABLE ALC_SYSTEM_MEM_STATS_IPRAN_AUX.AVMS_PERIODIC_TIME		          	IS 'Viene en el XML	equipment.AvailableMemoryStats';
COMMENT ON TABLE ALC_SYSTEM_MEM_STATS_IPRAN_AUX.AVMS_MONITORED_OBJECT_SITE_ID	  	IS 'Viene en el XML	equipment.AvailableMemoryStats';
COMMENT ON TABLE ALC_SYSTEM_MEM_STATS_IPRAN_AUX.AVMS_MONITORED_OBJECT_SITE_NAME		IS 'Viene en el XML	equipment.AvailableMemoryStats';
COMMENT ON TABLE ALC_SYSTEM_MEM_STATS_IPRAN_AUX.AVMS_AVAILABLE_MEMORY_PCT        	IS 'Se calcula --> AVMS_available_Memory/(AVMS_available_Memory+AVMS_allocated_Memory)) (%)';
COMMENT ON TABLE ALC_SYSTEM_MEM_STATS_IPRAN_AUX.AVMS_AVAILABLE_MEMORY_MB         	IS 'Se calcula --> AVMS_available_Memory/1048576) (MB)';
COMMENT ON TABLE ALC_SYSTEM_MEM_STATS_IPRAN_AUX.AMS_ALLOCATED_MEMORY		        	IS 'Viene en el XML	equipment.AllocatedMemoryStats (AMS)';
COMMENT ON TABLE ALC_SYSTEM_MEM_STATS_IPRAN_AUX.AMS_TIME_CAPTURED		            	IS 'Viene en el XML	equipment.AllocatedMemoryStats';
COMMENT ON TABLE ALC_SYSTEM_MEM_STATS_IPRAN_AUX.AMS_PERIODIC_TIME		            	IS 'Viene en el XML	equipment.AllocatedMemoryStats';
COMMENT ON TABLE ALC_SYSTEM_MEM_STATS_IPRAN_AUX.AMS_MONITORED_OBJECT_SITE_ID	  	IS 'Viene en el XML	equipment.AllocatedMemoryStats';
COMMENT ON TABLE ALC_SYSTEM_MEM_STATS_IPRAN_AUX.AMS_MONITORED_OBJECT_SITE_NAME		IS 'Viene en el XML	equipment.AllocatedMemoryStats';
COMMENT ON TABLE ALC_SYSTEM_MEM_STATS_IPRAN_AUX.AMS_ALLOCATED_MEMORY            	IS 'Se calcula --> AMS_allocated_Memory/1048576) (MB)';


CREATE TABLE ALC_SYSTEM_MEM_STATS_IPRAN_RAW(
  SYSTEM_MEMORY_USAGE	        NUMBER NOT NULL,
  TIME_CAPTURED	              NUMBER NOT NULL,
  PERIODIC_TIME	              NUMBER NOT NULL,
  MONITORED_OBJECT_SITE_ID	  VARCHAR2(50 CHAR) NOT NULL,
  MONITORED_OBJECT_SITE_NAME	VARCHAR2(50 CHAR) NOT NULL,
  SYSTEM_MEMORY_USAGE         NUMBER NOT NULL,
  SYSTEM_MEMORY_USAGEAVG      NUMBER NOT NULL
) NOCOMPRESS NOLOGGING;
-- TABLESPACE TBS_HOUR;

COMMENT ON TABLE ALC_SYSTEM_MEM_STATS_IPRAN_RAW IS'Medición: Medicion de la Memoria';

COMMENT ON TABLE ALC_SYSTEM_MEM_STATS_IPRAN_RAW.SMS_SYSTEM_MEMORY_USAGE	          IS 'Viene en el XML	equipment.SystemMemoryStats (SMS)';
COMMENT ON TABLE ALC_SYSTEM_MEM_STATS_IPRAN_RAW.SMS_TIME_CAPTURED		              IS 'Viene en el XML	equipment.SystemMemoryStats';
COMMENT ON TABLE ALC_SYSTEM_MEM_STATS_IPRAN_RAW.SMS_PERIODIC_TIME			            IS 'Viene en el XML	equipment.SystemMemoryStats';
COMMENT ON TABLE ALC_SYSTEM_MEM_STATS_IPRAN_RAW.SMS_MONITORED_OBJECT_SITE_ID		  IS 'Viene en el XML	equipment.SystemMemoryStats';
COMMENT ON TABLE ALC_SYSTEM_MEM_STATS_IPRAN_RAW.SMS_MONITORED_OBJECT_SITE_NAME		IS 'Viene en el XML	equipment.SystemMemoryStats';
COMMENT ON TABLE ALC_SYSTEM_MEM_STATS_IPRAN_RAW.SMS_SYSTEM_MEMORY_USAGE_MB       	IS 'Se calcula --> sms_system_Memory_Usage/1048576';
COMMENT ON TABLE ALC_SYSTEM_MEM_STATS_IPRAN_RAW.SMS_SYSTEM_MEMORY_USAGE_AVG      	IS 'Se calcula --> sms_system_Memory_Usage/(sms_available_Memory+sms_allocated_Memory)) (%)';	
COMMENT ON TABLE ALC_SYSTEM_MEM_STATS_IPRAN_RAW.AVMS_AVAILABLE_MEMORY		        	IS 'Viene en el XML	equipment.AvailableMemoryStats (AVMS)';
COMMENT ON TABLE ALC_SYSTEM_MEM_STATS_IPRAN_RAW.AVMS_TIME_CAPTURED		          	IS 'Viene en el XML	equipment.AvailableMemoryStats';
COMMENT ON TABLE ALC_SYSTEM_MEM_STATS_IPRAN_RAW.AVMS_PERIODIC_TIME		          	IS 'Viene en el XML	equipment.AvailableMemoryStats';
COMMENT ON TABLE ALC_SYSTEM_MEM_STATS_IPRAN_RAW.AVMS_MONITORED_OBJECT_SITE_ID	  	IS 'Viene en el XML	equipment.AvailableMemoryStats';
COMMENT ON TABLE ALC_SYSTEM_MEM_STATS_IPRAN_RAW.AVMS_MONITORED_OBJECT_SITE_NAME		IS 'Viene en el XML	equipment.AvailableMemoryStats';
COMMENT ON TABLE ALC_SYSTEM_MEM_STATS_IPRAN_RAW.AVMS_AVAILABLE_MEMORY_PCT        	IS 'Se calcula --> AVMS_available_Memory/(AVMS_available_Memory+AVMS_allocated_Memory)) (%)';
COMMENT ON TABLE ALC_SYSTEM_MEM_STATS_IPRAN_RAW.AVMS_AVAILABLE_MEMORY_MB         	IS 'Se calcula --> AVMS_available_Memory/1048576) (MB)';
COMMENT ON TABLE ALC_SYSTEM_MEM_STATS_IPRAN_RAW.AMS_ALLOCATED_MEMORY		        	IS 'Viene en el XML	equipment.AllocatedMemoryStats (AMS)';
COMMENT ON TABLE ALC_SYSTEM_MEM_STATS_IPRAN_RAW.AMS_TIME_CAPTURED		            	IS 'Viene en el XML	equipment.AllocatedMemoryStats';
COMMENT ON TABLE ALC_SYSTEM_MEM_STATS_IPRAN_RAW.AMS_PERIODIC_TIME		            	IS 'Viene en el XML	equipment.AllocatedMemoryStats';
COMMENT ON TABLE ALC_SYSTEM_MEM_STATS_IPRAN_RAW.AMS_MONITORED_OBJECT_SITE_ID	  	IS 'Viene en el XML	equipment.AllocatedMemoryStats';
COMMENT ON TABLE ALC_SYSTEM_MEM_STATS_IPRAN_RAW.AMS_MONITORED_OBJECT_SITE_NAME		IS 'Viene en el XML	equipment.AllocatedMemoryStats';
COMMENT ON TABLE ALC_SYSTEM_MEM_STATS_IPRAN_RAW.AMS_ALLOCATED_MEMORY            	IS 'Se calcula --> AMS_allocated_Memory/1048576) (MB)';