select length('MONITORED_OBJECT_POINTER') from dual;


create table ALC_MEDIA_INDEP_STATS_IPRAN_AUX(
  DROP_EVENTS_PERIODIC	        NUMBER,
  DROPPED_FRAMES_PERIODIC	      NUMBER,
  RECEIVED_PACKETS_PERIODIC	    NUMBER,
  TRANSMITTED_PACKETS_PERIODIC	NUMBER,
  RECEIVED_OCTETS_PERIODIC	    NUMBER,
  TRANSMITTEDOCTETS_PERIODIC	  NUMBER,
  REC_NON_UNICAST_PAC_PERIODIC	NUMBER,
  TRAN_NON_UNICAST_PAC_PERIODIC	NUMBER,
  RECEIVED_BAD_PACKETS_PERIODIC	NUMBER,
  TRAN_BAD_PACKETS_PERIODIC	    NUMBER,
  INPUT_SPEED	                  NUMBER,
  OUTPUT_SPEED	                NUMBER,
  DUPLEX	                      VARCHAR2(50 CHAR),
  DUPLEX_CHANGESPERIODIC	      NUMBER,
  TIME_CAPTURED	                NUMBER,
  PERIODIC_TIME	                NUMBER,
  MONITORED_OBJECT_POINTER	    VARCHAR2(50 CHAR),
  MONITORED_OBJECT_SITE_ID	    VARCHAR2(50 CHAR),
  MONITORED_OBJECT_SITENAME	    VARCHAR2(50 CHAR),
  IN_BANDWITH_UTIL              NUMBER,
  OUT_BANDWITH_UTIL             NUMBER,
  REC_OCTETS                    NUMBER,
  TRANS_OCTETS                  NUMBER
)nologging;

COMMENT ON TABLE ALC_MEDIA_INDEP_STATS_IPRAN_AUX IS 'Tabla auxiliar para hacer los calculos en forma automatica';
COMMENT ON COLUMN ALC_MEDIA_INDEP_STATS_IPRAN_AUX.REC_NON_UNICAST_PAC_PERIODIC IS 'Reescritura de la columna RECEIVED_NON_UNICAST_PACKETS_PERIODIC';
COMMENT ON COLUMN ALC_MEDIA_INDEP_STATS_IPRAN_AUX.TRAN_NON_UNICAST_PAC_PERIODIC IS 'Reescritura de la columna TRANSMITTED_NON_UNICAST_PACKETS_PERIODIC';
COMMENT ON COLUMN ALC_MEDIA_INDEP_STATS_IPRAN_AUX.TRAN_BAD_PACKETS_PERIODIC IS 'Reescritura de la columna TRANSMITTED_BAD_PACKETS_PERIODIC';
COMMENT ON COLUMN ALC_MEDIA_INDEP_STATS_IPRAN_AUX.MONITORED_OBJECT_SITE_ID IS 'TEXT(IP)';
COMMENT ON COLUMN ALC_MEDIA_INDEP_STATS_IPRAN_AUX.MONITORED_OBJECT_SITENAME IS 'TEXT(EQUIPO)';
COMMENT ON COLUMN ALC_MEDIA_INDEP_STATS_IPRAN_AUX.IN_BANDWITH_UTIL IS 'Se debe calcular con la fórmula --> 8*RECEIVED_OCTETS_PERIODIC/(OUTPUT_SPEED*900000)';
COMMENT ON COLUMN ALC_MEDIA_INDEP_STATS_IPRAN_AUX.OUT_BANDWITH_UTIL IS 'Se debe calcular con la fórmula --> 8*TRANSMITTED_OCTETS_PERIODIC/(OUTPUT_SPEED*900000)';
COMMENT ON COLUMN ALC_MEDIA_INDEP_STATS_IPRAN_AUX.REC_OCTETS IS 'Se debe calcular con la fórmula --> RECEIVED_OCTETS_PERIODIC/1048576	en (MB)';
COMMENT ON COLUMN ALC_MEDIA_INDEP_STATS_IPRAN_AUX. IS 'Se debe calcular con la fórmula --> TRANSMITTED_OCTETS_PERIODIC/1048576	en (MB)';