--
-- DROP TABLE ALC_SYSTEM_MEM_STATS_IPRAN_RAW;

CREATE TABLE ALC_SYSTEM_MEM_STATS_IPRAN_RAW(
  -- XML_SYSTEM_STATS SMS = SystemMemoryStats
  FECHA                       DATE,
  SYSTEM_MEMORY_USAGE	        NUMBER,
  SMS_TIME_CAPTURED		        NUMBER,
  SMS_PERIODIC_TIME		        NUMBER,
  MONITORED_OBJECT_SITE_ID	  VARCHAR2(50 CHAR) NOT NULL,
  MONITORED_OBJECT_SITE_NAME	VARCHAR2(50 CHAR) NOT NULL,
  SMS_SYSTEM_MEMORY_USAGE_MB  NUMBER,
  SMS_SYSTEM_MEMORY_USAGE_AVG NUMBER,
  -- XML_SYSTEM_STATS_1 AVMS = AvailableMemoryStats
  AVAILABLE_MEMORY		        NUMBER,
  AVMS_TIME_CAPTURED		      NUMBER,
  AVMS_PERIODIC_TIME		      NUMBER,
  AVMS_AVAILABLE_MEMORY_PCT   NUMBER,
  AVMS_AVAILABLE_MEMORY_MB    NUMBER,
  -- XML_SYSTEM_STATS_2 AMS = AllocatedMemoryStats
  ALLOCATED_MEMORY		        NUMBER,
  AMS_TIME_CAPTURED		        NUMBER,
  AMS_PERIODIC_TIME		        NUMBER,
  AMS_ALLOCATED_MEMORY_MB     NUMBER
) NOCOMPRESS NOLOGGING;
-- TABLESPACE TBS_AUXILIAR;

COMMENT ON TABLE ALC_SYSTEM_MEM_STATS_IPRAN_RAW IS'Medición: Medicion de la Memoria';
COMMENT ON COLUMN ALC_SYSTEM_MEM_STATS_IPRAN_RAW.SYSTEM_MEMORY_USAGE	        IS 'Viene en el XML	equipment.SystemMemoryStats (SMS)';
COMMENT ON COLUMN ALC_SYSTEM_MEM_STATS_IPRAN_RAW.SMS_TIME_CAPTURED		        IS 'Viene en el XML	equipment.SystemMemoryStats';
COMMENT ON COLUMN ALC_SYSTEM_MEM_STATS_IPRAN_RAW.SMS_PERIODIC_TIME			      IS 'Viene en el XML	equipment.SystemMemoryStats';
COMMENT ON COLUMN ALC_SYSTEM_MEM_STATS_IPRAN_RAW.MONITORED_OBJECT_SITE_ID		  IS 'Viene en el XML	equipment.SystemMemoryStats';
COMMENT ON COLUMN ALC_SYSTEM_MEM_STATS_IPRAN_RAW.MONITORED_OBJECT_SITE_NAME		IS 'Viene en el XML	equipment.SystemMemoryStats';
COMMENT ON COLUMN ALC_SYSTEM_MEM_STATS_IPRAN_RAW.SMS_SYSTEM_MEMORY_USAGE_MB   IS 'Se calcula --> sms_system_Memory_Usage/1048576';
COMMENT ON COLUMN ALC_SYSTEM_MEM_STATS_IPRAN_RAW.SMS_SYSTEM_MEMORY_USAGE_AVG  IS 'Se calcula --> sms_system_Memory_Usage/(sms_available_Memory+sms_allocated_Memory)) (%)';	
COMMENT ON COLUMN ALC_SYSTEM_MEM_STATS_IPRAN_RAW.AVAILABLE_MEMORY		        	IS 'Viene en el XML	equipment.AvailableMemoryStats (AVMS)';
COMMENT ON COLUMN ALC_SYSTEM_MEM_STATS_IPRAN_RAW.AVMS_TIME_CAPTURED		        IS 'Viene en el XML	equipment.AvailableMemoryStats';
COMMENT ON COLUMN ALC_SYSTEM_MEM_STATS_IPRAN_RAW.AVMS_PERIODIC_TIME		        IS 'Viene en el XML	equipment.AvailableMemoryStats';
COMMENT ON COLUMN ALC_SYSTEM_MEM_STATS_IPRAN_RAW.AVMS_AVAILABLE_MEMORY_PCT    IS 'Se calcula --> AVMS_available_Memory/(AVMS_available_Memory+AVMS_allocated_Memory)) (%)';
COMMENT ON COLUMN ALC_SYSTEM_MEM_STATS_IPRAN_RAW.AVMS_AVAILABLE_MEMORY_MB     IS 'Se calcula --> AVMS_available_Memory/1048576) (MB)';
COMMENT ON COLUMN ALC_SYSTEM_MEM_STATS_IPRAN_RAW.ALLOCATED_MEMORY		        	IS 'Viene en el XML	equipment.AllocatedMemoryStats (AMS)';
COMMENT ON COLUMN ALC_SYSTEM_MEM_STATS_IPRAN_RAW.AMS_TIME_CAPTURED		        IS 'Viene en el XML	equipment.AllocatedMemoryStats';
COMMENT ON COLUMN ALC_SYSTEM_MEM_STATS_IPRAN_RAW.AMS_PERIODIC_TIME		        IS 'Viene en el XML	equipment.AllocatedMemoryStats';
COMMENT ON COLUMN ALC_SYSTEM_MEM_STATS_IPRAN_RAW.AMS_ALLOCATED_MEMORY_MB      IS 'Se calcula --> AMS_allocated_Memory/1048576) (MB)';
--
-- POPULAR
-- 
insert into ALC_SYSTEM_MEM_STATS_IPRAN_RAW (FECHA,SYSTEM_MEMORY_USAGE,SMS_TIME_CAPTURED,SMS_PERIODIC_TIME,MONITORED_OBJECT_SITE_ID,
      MONITORED_OBJECT_SITE_NAME,SMS_SYSTEM_MEMORY_USAGE_MB,SMS_SYSTEM_MEMORY_USAGE_AVG,AVAILABLE_MEMORY,AVMS_TIME_CAPTURED,
      AVMS_PERIODIC_TIME,AVMS_AVAILABLE_MEMORY_PCT,AVMS_AVAILABLE_MEMORY_MB,ALLOCATED_MEMORY,AMS_TIME_CAPTURED,AMS_PERIODIC_TIME,
      AMS_ALLOCATED_MEMORY_MB)
select 
      -- XML_SYSTEM_STATS
      SMS.FECHA                                                                             FECHA,
      SMS.SYSTEM_MEMORY_USAGE	                                                              SYSTEM_MEMORY_USAGE,
      SMS.TIME_CAPTURED		                                                                  SMS_TIME_CAPTURED,
      SMS.PERIODIC_TIME		                                                                  SMS_PERIODIC_TIME,
      SMS.MONITORED_OBJECT_SITE_ID	                                                        MONITORED_OBJECT_SITE_ID,
      SMS.MONITORED_OBJECT_SITE_NAME	                                                      MONITORED_OBJECT_SITE_NAME,
      ROUND(SMS.SYSTEM_MEMORY_USAGE/1048576,2)                                              SMS_SYSTEM_MEMORY_USAGE_MB,
      ROUND(DECODE((AVMS.AVAILABLE_MEMORY + AMS.ALLOCATED_MEMORY),0,0,
            (SMS.SYSTEM_MEMORY_USAGE / (AVMS.AVAILABLE_MEMORY + AMS.ALLOCATED_MEMORY))),2)  SMS_SYSTEM_MEMORY_USAGE_AVG,
      -- XML_SYSTEM_STATS_1
      AVMS.AVAILABLE_MEMORY		                                                              AVAILABLE_MEMORY,
      AVMS.TIME_CAPTURED		                                                                AVMS_TIME_CAPTURED,
      AVMS.PERIODIC_TIME		                                                                AVMS_PERIODIC_TIME,
      ROUND(DECODE((AVMS.AVAILABLE_MEMORY + AMS.ALLOCATED_MEMORY),0,0,
            (AVMS.AVAILABLE_MEMORY / (AVMS.AVAILABLE_MEMORY + AMS.ALLOCATED_MEMORY))),2)    AVMS_AVAILABLE_MEMORY_PCT,
      ROUND(AVMS.AVAILABLE_MEMORY/1048576,2)                                                AVMS_AVAILABLE_MEMORY_MB,
      -- XML_SYSTEM_STATS_2
      AMS.ALLOCATED_MEMORY		                                                              ALLOCATED_MEMORY,
      AMS.TIME_CAPTURED		                                                                  AMS_TIME_CAPTURED,
      AMS.PERIODIC_TIME		                                                                  AMS_PERIODIC_TIME,
      ROUND(AMS.ALLOCATED_MEMORY / 1048576,2)                                               AMS_ALLOCATED_MEMORY_MB

from  XML_SYSTEM_STATS SMS,
      XML_SYSTEM_STATS_1 AVMS,
      XML_SYSTEM_STATS_2 AMS
where SMS.FECHA = AVMS.FECHA (+)
and   AVMS.FECHA = AMS.FECHA (+)
and   SMS.MONITORED_OBJECT_SITE_NAME = AVMS.MONITORED_OBJECT_SITE_NAME (+)
and   AVMS.MONITORED_OBJECT_SITE_NAME = AMS.MONITORED_OBJECT_SITE_NAME (+);
--LOG ERRORS INTO ERR$_ALC_S_M_S_IPRAN_R ('INSERT') REJECT LIMIT UNLIMITED;

