-- Se llena con datos de las tablas ALC_SYSTEM_CPU_STATS_IPRAN_RAW y ALC_SYSTEM_MEM_STATS_IPRAN_RAW
--
-- DROP TABLE ALC_STATS_CPUMEM_HOUR PURGE;
--
CREATE TABLE ALC_STATS_CPUMEM_HOUR(
  --ALC_SYSTEM_CPU_STATS_IPRAN_RAW
  FECHA	                      DATE,
  MONITORED_OBJECT_SITE_ID	  VARCHAR2(50 CHAR),
  MONITORED_OBJECT_SITE_NAME	VARCHAR2(50 CHAR),
  SYSTEM_CPU_USAGE	          NUMBER, --AVG(SYSTEM_CPU_USAGE)
  SYSTEM_CPU_USAGE_AVG	      NUMBER, --AVG(SYSTEM_CPU_USAGE)
  SYSTEM_CPU_USAGE_MAX	      NUMBER, --MAX(SYSTEM_CPU_USAGE)
  -- ALC_SYSTEM_MEM_STATS_IPRAN_RAW
  SYSTEM_MEMORY_USAGE	        NUMBER,
  SYSTEM_MEMORY_USAGE_AVG_MB	NUMBER, --AVG(SYSTEM_MEMORY_USAGE)
  SYSTEM_MEMORY_USAGE_MAX_MB	NUMBER, --MAX(SYSTEM_MEMORY_USAGE)
  SYSTEM_MEMORY_USAGE_AVG_PCT	NUMBER, --AVG(SMS_SYSTEM_MEMORY_USAGE_AVG)
  SYSTEM_MEMORY_USAGE_MAX_PCT NUMBER, --MAX(SMS_SYSTEM_MEMORY_USAGE_AVG)
  --
  AVAILABLE_MEMORY	          NUMBER,  --AVG(AVAILABLE_MEMORY)
  AVAILABLE_MEMORY_AVG_MB	    NUMBER, --AVG(AVMS_AVAILABLE_MEMORY_MB)
  AVAILABLE_MEMORY_MAX_MB	    NUMBER, --MAX(AVMS_AVAILABLE_MEMORY_MB)
  AVAILABLE_MEMORY_AVG_PCT	  NUMBER,  --AVG(AVMS_AVAILABLE_MEMORY_PCT)
  AVAILABLE_MEMORY_MAX_PCT	  NUMBER, --MAX(AVMS_AVAILABLE_MEMORY_PCT)
  --
  ALLOCATED_MEMORY	          NUMBER,  --AVG(ALLOCATED_MEMORY	NUMBER)
  ALLOCATED_MEMORY_MB	        NUMBER --SUM(AMS_ALLOCATED_MEMORY_MB) ??????
)NOLOGGING NOCOMPRESS;
-- TABLESPACE TBS_HOUR;

COMMENT ON TABLE ALC_STATS_CPUMEM_HOUR IS 'Se llena con datos de las tablas ALC_SYSTEM_CPU_STATS_IPRAN_RAW y ALC_SYSTEM_MEM_STATS_IPRAN_RAW';


SELECT  --ALC_SYSTEM_CPU_STATS_IPRAN_RAW
        TO_CHAR(CPU.FECHA,'DD.MM.YYYY HH24')	        FECHA,
        CPU.MONITORED_OBJECT_SITE_ID,
        CPU.MONITORED_OBJECT_SITE_NAME,
        ROUND(AVG(CPU.SYSTEM_CPU_USAGE),2)	          SYSTEM_CPU_USAGE, --AVG(SYSTEM_CPU_USAGE)
        ROUND(AVG(CPU.SYSTEM_CPU_USAGE),2)	          SYSTEM_CPU_USAGE_AVG, --AVG(SYSTEM_CPU_USAGE)
        ROUND(MAX(CPU.SYSTEM_CPU_USAGE),2)	          SYSTEM_CPU_USAGE_MAX, --MAX(SYSTEM_CPU_USAGE)
        -- ALC_SYSTEM_MEM_STATS_IPRAN_RAW
        ROUND(AVG(MEM.SYSTEM_MEMORY_USAGE),2)	        SYSTEM_MEMORY_USAGE,
        ROUND(AVG(MEM.SMS_SYSTEM_MEMORY_USAGE_MB),2)	SYSTEM_MEMORY_USAGE_AVG_MB, --AVG(SYSTEM_MEMORY_USAGE_MB)
        ROUND(MAX(MEM.SMS_SYSTEM_MEMORY_USAGE_MB),2)	SYSTEM_MEMORY_USAGE_MAX_MB, --MAX(SYSTEM_MEMORY_USAGE_MB)
        ROUND(AVG(MEM.SMS_SYSTEM_MEMORY_USAGE_AVG),2)	SYSTEM_MEMORY_USAGE_AVG_PCT, --AVG(SMS_SYSTEM_MEMORY_USAGE_AVG)
        ROUND(MAX(MEM.SMS_SYSTEM_MEMORY_USAGE_AVG),2) SYSTEM_MEMORY_USAGE_MAX, --MAX(SMS_SYSTEM_MEMORY_USAGE_AVG)
        --
        ROUND(AVG(MEM.AVAILABLE_MEMORY),2)	          AVAILABLE_MEMORY,  --AVG(AVAILABLE_MEMORY)
        ROUND(AVG(MEM.AVMS_AVAILABLE_MEMORY_MB),2)	  AVAILABLE_MEMORY_AVG_MB, --AVG(AVMS_AVAILABLE_MEMORY_MB)
        ROUND(MAX(MEM.AVMS_AVAILABLE_MEMORY_MB),2)	  AVAILABLE_MEMORY_MAX_MB, --MAX(AVMS_AVAILABLE_MEMORY_MB)
        ROUND(AVG(MEM.AVMS_AVAILABLE_MEMORY_PCT),2)	  AVAILABLE_MEMORY_AVG_PCT,  --AVG(AVMS_AVAILABLE_MEMORY_PCT)
        ROUND(MAX(MEM.AVMS_AVAILABLE_MEMORY_PCT),2)	  AVAILABLE_MEMORY_MAX_PCT, --MAX(AVMS_AVAILABLE_MEMORY_PCT)
        --
        ROUND(AVG(MEM.ALLOCATED_MEMORY),2)	          ALLOCATED_MEMORY,  --AVG(ALLOCATED_MEMORY	NUMBER)
        ROUND(SUM(MEM.AMS_ALLOCATED_MEMORY_MB),2)     ALLOCATED_MEMORY_MB
FROM  ALC_SYSTEM_CPU_STATS_IPRAN_RAW CPU,
      ALC_SYSTEM_MEM_STATS_IPRAN_RAW MEM
WHERE TO_CHAR(CPU.FECHA,'DD.MM.YYYY HH24')  = '05.12.2016 17'
AND   TO_CHAR(CPU.FECHA,'DD.MM.YYYY HH24')  = TO_CHAR(MEM.FECHA,'DD.MM.YYYY HH24')
AND   CPU.MONITORED_OBJECT_SITE_ID          = MEM.MONITORED_OBJECT_SITE_ID
AND   CPU.MONITORED_OBJECT_SITE_NAME        = MEM.MONITORED_OBJECT_SITE_NAME
GROUP BY  TO_CHAR(CPU.FECHA,'DD.MM.YYYY HH24'),
          CPU.MONITORED_OBJECT_SITE_ID,
          CPU.MONITORED_OBJECT_SITE_NAME;
          
-- DROP TABLE ALC_STATS_CPUMEM_DAY PURGE;
--
CREATE TABLE ALC_STATS_CPUMEM_DAY(
  FECHA	                      DATE,
  MONITORED_OBJECT_SITE_ID	  VARCHAR2(50 CHAR),
  MONITORED_OBJECT_SITE_NAME	VARCHAR2(50 CHAR),
  SYSTEM_CPU_USAGE	          NUMBER,
  SYSTEM_CPU_USAGE_AVG	      NUMBER,
  SYSTEM_CPU_USAGE_MAX	      NUMBER,
  SYSTEM_MEMORY_USAGE	        NUMBER,
  SYSTEM_MEMORY_USAGE_AVG_MB	NUMBER,
  SYSTEM_MEMORY_USAGE_MAX_MB	NUMBER,
  SYSTEM_MEMORY_USAGE_AVG_PCT	NUMBER,
  SYSTEM_MEMORY_USAGE_MAX_PCT NUMBER,
  AVAILABLE_MEMORY	          NUMBER,
  AVAILABLE_MEMORY_AVG_MB	    NUMBER,
  AVAILABLE_MEMORY_MAX_MB	    NUMBER,
  AVAILABLE_MEMORY_AVG_PCT	  NUMBER,
  AVAILABLE_MEMORY_MAX_PCT	  NUMBER,
  ALLOCATED_MEMORY	          NUMBER,
  ALLOCATED_MEMORY_MB	        NUMBER
)NOLOGGING NOCOMPRESS;
-- TABLESPACE TBS_DAY;

COMMENT ON TABLE ALC_STATS_CPUMEM_DAY IS 'Se llena con datos de las tablas ALC_STATS_CPUMEM_HOUR sumarizados a nivel DAY';
--
--
SELECT  TRUNC(FECHA) FECHA,
        MONITORED_OBJECT_SITE_ID,
        MONITORED_OBJECT_SITE_NAME,
        ROUND(AVG(SYSTEM_CPU_USAGE),2)	          SYSTEM_CPU_USAGE,
        ROUND(AVG(SYSTEM_CPU_USAGE_AVG),2)	      SYSTEM_CPU_USAGE_AVG,
        ROUND(MAX(SYSTEM_CPU_USAGE_MAX),2)	      SYSTEM_CPU_USAGE_MAX,
        ROUND(AVG(SYSTEM_MEMORY_USAGE),2)	        SYSTEM_MEMORY_USAGE,
        ROUND(AVG(SYSTEM_MEMORY_USAGE_AVG_MB),2)	SYSTEM_MEMORY_USAGE_AVG_MB,
        ROUND(MAX(SYSTEM_MEMORY_USAGE_MAX_MB),2)	SYSTEM_MEMORY_USAGE_MAX_MB,
        ROUND(AVG(SYSTEM_MEMORY_USAGE_AVG_PCT),2)	SYSTEM_MEMORY_USAGE_AVG_PCT,
        ROUND(MAX(SYSTEM_MEMORY_USAGE_MAX_PCT),2) SYSTEM_MEMORY_USAGE_MAX_PCT,
        ROUND(AVG(AVAILABLE_MEMORY),2)	          AVAILABLE_MEMORY,
        ROUND(AVG(AVAILABLE_MEMORY_AVG_MB),2)	    AVAILABLE_MEMORY_AVG_MB,
        ROUND(MAX(AVAILABLE_MEMORY_MAX_MB),2)	    AVAILABLE_MEMORY_MAX_MB,
        ROUND(AVG(AVAILABLE_MEMORY_AVG_PCT),2)	  AVAILABLE_MEMORY_AVG_PCT,
        ROUND(MAX(AVAILABLE_MEMORY_MAX_PCT),2)	  AVAILABLE_MEMORY_MAX_PCT,
        ROUND(AVG(ALLOCATED_MEMORY),2)	          ALLOCATED_MEMORY,
        ROUND(SUM(ALLOCATED_MEMORY_MB),2)         ALLOCATED_MEMORY_MB
FROM  ALC_STATS_CPUMEM_HOUR
WHERE TRUNC(FECHA) = TO_DATE('04.12.2016') 
GROUP BY  TRUNC(FECHA),
          MONITORED_OBJECT_SITE_ID,
          MONITORED_OBJECT_SITE_NAME;
          
--
--
CREATE TABLE ALC_STATS_CPUMEM_BH(
  FECHA	                      DATE,
  MONITORED_OBJECT_SITE_ID	  VARCHAR2(50 CHAR),
  MONITORED_OBJECT_SITE_NAME	VARCHAR2(50 CHAR),
  SYSTEM_CPU_USAGE	          NUMBER,
  SYSTEM_CPU_USAGE_AVG	      NUMBER,
  SYSTEM_CPU_USAGE_MAX	      NUMBER,
  SYSTEM_MEMORY_USAGE	        NUMBER,
  SYSTEM_MEMORY_USAGE_AVG_MB	NUMBER,
  SYSTEM_MEMORY_USAGE_MAX_MB	NUMBER,
  SYSTEM_MEMORY_USAGE_AVG_PCT	NUMBER,
  SYSTEM_MEMORY_USAGE_MAX_PCT NUMBER,
  AVAILABLE_MEMORY	          NUMBER,
  AVAILABLE_MEMORY_AVG_MB	    NUMBER,
  AVAILABLE_MEMORY_MAX_MB	    NUMBER,
  AVAILABLE_MEMORY_AVG_PCT	  NUMBER,
  AVAILABLE_MEMORY_MAX_PCT	  NUMBER,
  ALLOCATED_MEMORY	          NUMBER,
  ALLOCATED_MEMORY_MB	        NUMBER
)NOLOGGING NOCOMPRESS;
-- TABLESPACE TBS_DAY;

COMMENT ON TABLE ALC_STATS_CPUMEM_BH IS 'Se llena con datos de las tablas ALC_STATS_CPUMEM_HOUR sumarizados a nivel BH';

SELECT  FECHA,
        MONITORED_OBJECT_SITE_ID,
        MONITORED_OBJECT_SITE_NAME,
        SYSTEM_CPU_USAGE,
        SYSTEM_CPU_USAGE_AVG,
        SYSTEM_CPU_USAGE_MAX,
        SYSTEM_MEMORY_USAGE,
        SYSTEM_MEMORY_USAGE_AVG_MB,
        SYSTEM_MEMORY_USAGE_MAX_MB,
        SYSTEM_MEMORY_USAGE_AVG_PCT,
        SYSTEM_MEMORY_USAGE_MAX_PCT,
        AVAILABLE_MEMORY,
        AVAILABLE_MEMORY_AVG_MB,
        AVAILABLE_MEMORY_MAX_MB,
        AVAILABLE_MEMORY_AVG_PCT,
        AVAILABLE_MEMORY_MAX_PCT,
        ALLOCATED_MEMORY,
        ALLOCATED_MEMORY_MB
FROM  (SELECT FECHA,
              MONITORED_OBJECT_SITE_ID,
              MONITORED_OBJECT_SITE_NAME,
              SYSTEM_CPU_USAGE,
              SYSTEM_CPU_USAGE_AVG,
              SYSTEM_CPU_USAGE_MAX,
              SYSTEM_MEMORY_USAGE,
              SYSTEM_MEMORY_USAGE_AVG_MB,
              SYSTEM_MEMORY_USAGE_MAX_MB,
              SYSTEM_MEMORY_USAGE_AVG_PCT,
              SYSTEM_MEMORY_USAGE_MAX_PCT,
              AVAILABLE_MEMORY,
              AVAILABLE_MEMORY_AVG_MB,
              AVAILABLE_MEMORY_MAX_MB,
              AVAILABLE_MEMORY_AVG_PCT,
              AVAILABLE_MEMORY_MAX_PCT,
              ALLOCATED_MEMORY,
              ALLOCATED_MEMORY_MB,
              ROW_NUMBER() OVER (PARTITION BY  TRUNC(FECHA),
                                              MONITORED_OBJECT_SITE_ID,
                                              MONITORED_OBJECT_SITE_NAME
                                ORDER BY  SYSTEM_CPU_USAGE DESC) RN
      FROM  ALC_STATS_CPUMEM_HOUR
      WHERE TRUNC(FECHA) = TO_DATE('05.12.2016')
    )
WHERE RN = 1;

--
--
CREATE TABLE ALC_STATS_CPUMEM_IBHW(
  FECHA	                      DATE,
  MONITORED_OBJECT_SITE_ID	  VARCHAR2(50 CHAR),
  MONITORED_OBJECT_SITE_NAME	VARCHAR2(50 CHAR),
  SYSTEM_CPU_USAGE	          NUMBER,
  SYSTEM_CPU_USAGE_AVG	      NUMBER,
  SYSTEM_CPU_USAGE_MAX	      NUMBER,
  SYSTEM_MEMORY_USAGE	        NUMBER,
  SYSTEM_MEMORY_USAGE_AVG_MB	NUMBER,
  SYSTEM_MEMORY_USAGE_MAX_MB	NUMBER,
  SYSTEM_MEMORY_USAGE_AVG_PCT	NUMBER,
  SYSTEM_MEMORY_USAGE_MAX_PCT NUMBER,
  AVAILABLE_MEMORY	          NUMBER,
  AVAILABLE_MEMORY_AVG_MB	    NUMBER,
  AVAILABLE_MEMORY_MAX_MB	    NUMBER,
  AVAILABLE_MEMORY_AVG_PCT	  NUMBER,
  AVAILABLE_MEMORY_MAX_PCT	  NUMBER,
  ALLOCATED_MEMORY	          NUMBER,
  ALLOCATED_MEMORY_MB	        NUMBER
)NOLOGGING NOCOMPRESS;
-- TABLESPACE TBS_SUMMARY;

COMMENT ON TABLE ALC_STATS_CPUMEM_IBHW IS 'Se llena con datos de las tablas ALC_STATS_CPUMEM_BH sumarizados a nivel IBHW';

SELECT  FECHA,
        MONITORED_OBJECT_SITE_ID,
        MONITORED_OBJECT_SITE_NAME,
        ROUND(AVG(SYSTEM_CPU_USAGE),2)	          SYSTEM_CPU_USAGE,
        ROUND(AVG(SYSTEM_CPU_USAGE_AVG),2)	      SYSTEM_CPU_USAGE_AVG,
        ROUND(MAX(SYSTEM_CPU_USAGE_MAX),2)	      SYSTEM_CPU_USAGE_MAX,
        ROUND(AVG(SYSTEM_MEMORY_USAGE),2)	        SYSTEM_MEMORY_USAGE,
        ROUND(AVG(SYSTEM_MEMORY_USAGE_AVG_MB),2)	SYSTEM_MEMORY_USAGE_AVG_MB,
        ROUND(MAX(SYSTEM_MEMORY_USAGE_MAX_MB),2)	SYSTEM_MEMORY_USAGE_MAX_MB,
        ROUND(AVG(SYSTEM_MEMORY_USAGE_AVG_PCT),2)	SYSTEM_MEMORY_USAGE_AVG_PCT,
        ROUND(MAX(SYSTEM_MEMORY_USAGE_MAX_PCT),2) SYSTEM_MEMORY_USAGE_MAX_PCT,
        ROUND(AVG(AVAILABLE_MEMORY),2)	          AVAILABLE_MEMORY,
        ROUND(AVG(AVAILABLE_MEMORY_AVG_MB),2)	    AVAILABLE_MEMORY_AVG_MB,
        ROUND(MAX(AVAILABLE_MEMORY_MAX_MB),2)	    AVAILABLE_MEMORY_MAX_MB,
        ROUND(AVG(AVAILABLE_MEMORY_AVG_PCT),2)	  AVAILABLE_MEMORY_AVG_PCT,
        ROUND(MAX(AVAILABLE_MEMORY_MAX_PCT),2)	  AVAILABLE_MEMORY_MAX_PCT,
        ROUND(AVG(ALLOCATED_MEMORY),2)	          ALLOCATED_MEMORY,
        ROUND(SUM(ALLOCATED_MEMORY_MB),2)         ALLOCATED_MEMORY_MB
FROM  (SELECT '05.12.2016'  FECHA,
              MONITORED_OBJECT_SITE_ID,
              MONITORED_OBJECT_SITE_NAME,
              SYSTEM_CPU_USAGE,
              SYSTEM_CPU_USAGE_AVG,
              SYSTEM_CPU_USAGE_MAX,
              SYSTEM_MEMORY_USAGE,
              SYSTEM_MEMORY_USAGE_AVG_MB,
              SYSTEM_MEMORY_USAGE_MAX_MB,
              SYSTEM_MEMORY_USAGE_AVG_PCT,
              SYSTEM_MEMORY_USAGE_MAX_PCT,
              AVAILABLE_MEMORY,
              AVAILABLE_MEMORY_AVG_MB,
              AVAILABLE_MEMORY_MAX_MB,
              AVAILABLE_MEMORY_AVG_PCT,
              AVAILABLE_MEMORY_MAX_PCT,
              ALLOCATED_MEMORY,
              ALLOCATED_MEMORY_MB,
              ROW_NUMBER() OVER (PARTITION BY  TRUNC(FECHA),
                                              MONITORED_OBJECT_SITE_ID,
                                              MONITORED_OBJECT_SITE_NAME
                                ORDER BY  SYSTEM_CPU_USAGE DESC) RN
      FROM  ALC_STATS_CPUMEM_HOUR
      WHERE TRUNC(FECHA) = TO_DATE('05.12.2016')
    )
WHERE RN <= 3
GROUP BY  FECHA,
          MONITORED_OBJECT_SITE_ID,
          MONITORED_OBJECT_SITE_NAME;



