DROP TABLE ALC_STATS_IPRAN_HOUR_TEMP PURGE;

  CREATE TABLE ALC_STATS_IPRAN_HOUR_TEMP 
   (	FECHA DATE NOT NULL ENABLE, 
	MONITORED_OBJECT_POINTER VARCHAR2(500 CHAR) NOT NULL ENABLE, 
	MONITORED_OBJECT_SITEID VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	MONITORED_OBJECT_SITE_NAME VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	DROP_EVENTS_PERIODIC NUMBER NOT NULL ENABLE, 
	DROPPED_FRAMES_PERIODIC NUMBER NOT NULL ENABLE, 
	RECEIVED_PACKETS_PERIODIC NUMBER NOT NULL ENABLE, 
	TRANSMITTED_PACKETS_PERIODIC NUMBER NOT NULL ENABLE, 
	RECEIVED_OCTETS_PERIODIC NUMBER NOT NULL ENABLE, 
	TRANSMITTED_OCTETS_PERIODIC NUMBER NOT NULL ENABLE, 
	RECEIVED_NON_UNI_PACK_PERIODIC NUMBER NOT NULL ENABLE, 
	TRANS_NON_UNI_PACK_PERIODIC NUMBER NOT NULL ENABLE, 
	RECEIVED_BAD_PACKETS_PERIODIC NUMBER NOT NULL ENABLE, 
	TRANS_BAD_PACKETS_PERIODIC NUMBER NOT NULL ENABLE, 
	INPUT_SPEED NUMBER NOT NULL ENABLE, 
	OUTPUT_SPEED NUMBER NOT NULL ENABLE, 
	IN_BANDWITH_UTIL NUMBER NOT NULL ENABLE, 
	OUT_BANDWITH_UTIL NUMBER NOT NULL ENABLE, 
	REC_OCTETS NUMBER NOT NULL ENABLE, 
	TRANS_OCTETS NUMBER NOT NULL ENABLE
   ) 
 NOCOMPRESS NOLOGGING
 PARTITION BY RANGE (FECHA) 
 INTERVAL(NUMTODSINTERVAL(1, 'HOUR'))
(
  PARTITION ALCSTATSIPRANHOUR_FIRST VALUES LESS THAN (TO_DATE('30.12.2016','DD.MM.YYYY'))
)
  TABLESPACE DEVELOPER ;

   COMMENT ON COLUMN ALC_STATS_IPRAN_HOUR_TEMP.RECEIVED_NON_UNI_PACK_PERIODIC IS 'Reescritura de la columna receivedNonUnicastPacketsPeriodic por superar la cantidad de caracteres permitidos para nombrar un objeto';
   COMMENT ON COLUMN ALC_STATS_IPRAN_HOUR_TEMP.TRANS_NON_UNI_PACK_PERIODIC IS 'Reescritura de la columna transmittedNonUnicastPacketsPeriodic por superar la cantidad de caracteres permitidos para nombrar un objeto';
   COMMENT ON COLUMN ALC_STATS_IPRAN_HOUR_TEMP.TRANS_BAD_PACKETS_PERIODIC IS 'Reescritura de la columna transmittedBadPacketsPeriodic por superar la cantidad de caracteres permitidos para nombrar un objeto';
   COMMENT ON TABLE ALC_STATS_IPRAN_HOUR_TEMP  IS 'Se llena con datos de ALC_MEDIA_INDP_STATS_IPRAN_RAW';


--
 -- check we'll be ok
 --
 exec dbms_redefinition.can_redef_table(user, 'ALC_STATS_IPRAN_HOUR_TEMP');


--
-- start the copy of all data
--
begin
    dbms_redefinition.start_redef_table(
    uname      => user,
    orig_table => 'ALC_STATS_IPRAN_HOUR',
   int_table  => 'ALC_STATS_IPRAN_HOUR_TEMP');
end;


