-- select length('ALC_MEDIA_INDP_STATS_IPRAN_raw') from dual;
--
-- DROP TABLE ALC_MEDIA_INDP_STATS_IPRAN_AUX
--
create table ALC_MEDIA_INDP_STATS_IPRAN_AUX(
  DROP_EVENTS_PERIODIC	        NUMBER  DEFAULT 0 NOT NULL,
  DROPPED_FRAMES_PERIODIC	      NUMBER  DEFAULT 0 NOT NULL,
  RECEIVED_PACKETS_PERIODIC	    NUMBER  DEFAULT 0 NOT NULL,
  TRANSMITTED_PACKETS_PERIODIC	NUMBER  DEFAULT 0 NOT NULL,
  RECEIVED_OCTETS_PERIODIC	    NUMBER  DEFAULT 0 NOT NULL,
  TRANSMITTED_OCTETS_PERIODIC	  NUMBER  DEFAULT 0 NOT NULL,
  REC_NON_UNICAST_PAC_PERIODIC	NUMBER  DEFAULT 0 NOT NULL,
  TRAN_NON_UNICAST_PAC_PERIODIC	NUMBER  DEFAULT 0 NOT NULL,
  RECEIVED_BAD_PACKETS_PERIODIC	NUMBER  DEFAULT 0 NOT NULL,
  TRAN_BAD_PACKETS_PERIODIC	    NUMBER  DEFAULT 0 NOT NULL,
  INPUT_SPEED	                  NUMBER  DEFAULT 0 NOT NULL,
  OUTPUT_SPEED	                NUMBER  DEFAULT 0 NOT NULL,
  DUPLEX	                      VARCHAR2(50 CHAR) NOT NULL,
  DUPLEX_CHANGES_PERIODIC	      NUMBER  DEFAULT 0 NOT NULL,
  TIME_CAPTURED	                NUMBER  DEFAULT 0 NOT NULL,
  PERIODIC_TIME	                NUMBER  DEFAULT 0 NOT NULL,
  MONITORED_OBJECT_POINTER	    VARCHAR2(50 CHAR) NOT NULL,
  MONITORED_OBJECT_SITE_ID	    VARCHAR2(50 CHAR) NOT NULL,
  MONITORED_OBJECT_SITENAME	    VARCHAR2(50 CHAR) NOT NULL,
  IN_BANDWITH_UTIL              NUMBER  GENERATED ALWAYS AS (8*RECEIVED_OCTETS_PERIODIC/(OUTPUT_SPEED*900000)),
  OUT_BANDWITH_UTIL             NUMBER  GENERATED ALWAYS AS (8*TRANSMITTED_OCTETS_PERIODIC/(OUTPUT_SPEED*900000)),
  REC_OCTETS                    NUMBER  GENERATED ALWAYS AS (RECEIVED_OCTETS_PERIODIC/1048576),
  TRANS_OCTETS                  NUMBER  GENERATED ALWAYS AS (TRANSMITTED_OCTETS_PERIODIC/1048576)
)NOCOMPRESS nologging;

COMMENT ON TABLE ALC_MEDIA_INDP_STATS_IPRAN_AUX IS 'Tabla auxiliar para hacer los calculos en forma automatica';
COMMENT ON COLUMN ALC_MEDIA_INDP_STATS_IPRAN_AUX.REC_NON_UNICAST_PAC_PERIODIC IS 'Reescritura de la columna RECEIVED_NON_UNICAST_PACKETS_PERIODIC';
COMMENT ON COLUMN ALC_MEDIA_INDP_STATS_IPRAN_AUX.TRAN_NON_UNICAST_PAC_PERIODIC IS 'Reescritura de la columna TRANSMITTED_NON_UNICAST_PACKETS_PERIODIC';
COMMENT ON COLUMN ALC_MEDIA_INDP_STATS_IPRAN_AUX.TRAN_BAD_PACKETS_PERIODIC IS 'Reescritura de la columna TRANSMITTED_BAD_PACKETS_PERIODIC';
COMMENT ON COLUMN ALC_MEDIA_INDP_STATS_IPRAN_AUX.MONITORED_OBJECT_SITE_ID IS 'TEXT(IP)';
COMMENT ON COLUMN ALC_MEDIA_INDP_STATS_IPRAN_AUX.MONITORED_OBJECT_SITENAME IS 'TEXT(EQUIPO)';
COMMENT ON COLUMN ALC_MEDIA_INDP_STATS_IPRAN_AUX.IN_BANDWITH_UTIL IS 'Se debe calcular con la fórmula --> 8*RECEIVED_OCTETS_PERIODIC/(OUTPUT_SPEED*900000)';
COMMENT ON COLUMN ALC_MEDIA_INDP_STATS_IPRAN_AUX.OUT_BANDWITH_UTIL IS 'Se debe calcular con la fórmula --> 8*TRANSMITTED_OCTETS_PERIODIC/(OUTPUT_SPEED*900000)';
COMMENT ON COLUMN ALC_MEDIA_INDP_STATS_IPRAN_AUX.REC_OCTETS IS 'Se debe calcular con la fórmula --> RECEIVED_OCTETS_PERIODIC/1048576	en (MB)';
COMMENT ON COLUMN ALC_MEDIA_INDP_STATS_IPRAN_AUX.TRANS_OCTETS IS 'Se debe calcular con la fórmula --> TRANSMITTED_OCTETS_PERIODIC/1048576	en (MB)';
--
-- DROP TABLE ALC_MEDIA_INDP_STATS_IPRAN_RAW
--
create table ALC_MEDIA_INDP_STATS_IPRAN_RAW(
  DROP_EVENTS_PERIODIC	        NUMBER  DEFAULT 0 NOT NULL,
  DROPPED_FRAMES_PERIODIC	      NUMBER  DEFAULT 0 NOT NULL,
  RECEIVED_PACKETS_PERIODIC	    NUMBER  DEFAULT 0 NOT NULL,
  TRANSMITTED_PACKETS_PERIODIC	NUMBER  DEFAULT 0 NOT NULL,
  RECEIVED_OCTETS_PERIODIC	    NUMBER  DEFAULT 0 NOT NULL,
  TRANSMITTED_OCTETS_PERIODIC	  NUMBER  DEFAULT 0 NOT NULL,
  REC_NON_UNICAST_PAC_PERIODIC	NUMBER  DEFAULT 0 NOT NULL,
  TRAN_NON_UNICAST_PAC_PERIODIC	NUMBER  DEFAULT 0 NOT NULL,
  RECEIVED_BAD_PACKETS_PERIODIC	NUMBER  DEFAULT 0 NOT NULL,
  TRAN_BAD_PACKETS_PERIODIC	    NUMBER  DEFAULT 0 NOT NULL,
  INPUT_SPEED	                  NUMBER  DEFAULT 0 NOT NULL,
  OUTPUT_SPEED	                NUMBER  DEFAULT 0 NOT NULL,
  DUPLEX	                      VARCHAR2(50 CHAR) NOT NULL,
  DUPLEX_CHANGESPERIODIC	      NUMBER  DEFAULT 0 NOT NULL,
  TIME_CAPTURED	                NUMBER  DEFAULT 0 NOT NULL,
  PERIODIC_TIME	                NUMBER  DEFAULT 0 NOT NULL,
  MONITORED_OBJECT_POINTER	    VARCHAR2(50 CHAR) NOT NULL,
  MONITORED_OBJECT_SITE_ID	    VARCHAR2(50 CHAR) NOT NULL,
  MONITORED_OBJECT_SITENAME	    VARCHAR2(50 CHAR) NOT NULL,
  IN_BANDWITH_UTIL              NUMBER  DEFAULT 0 NOT NULL,
  OUT_BANDWITH_UTIL             NUMBER  DEFAULT 0 NOT NULL,
  REC_OCTETS                    NUMBER  DEFAULT 0 NOT NULL,
  TRANS_OCTETS                  NUMBER  DEFAULT 0 NOT NULL
)NOCOMPRESS nologging;

COMMENT ON TABLE ALC_MEDIA_INDP_STATS_IPRAN_RAW IS 'Medicion:  equipment.MediaIndependentStats';
COMMENT ON COLUMN ALC_MEDIA_INDP_STATS_IPRAN_RAW.REC_NON_UNICAST_PAC_PERIODIC IS 'Reescritura de la columna RECEIVED_NON_UNICAST_PACKETS_PERIODIC';
COMMENT ON COLUMN ALC_MEDIA_INDP_STATS_IPRAN_RAW.TRAN_NON_UNICAST_PAC_PERIODIC IS 'Reescritura de la columna TRANSMITTED_NON_UNICAST_PACKETS_PERIODIC';
COMMENT ON COLUMN ALC_MEDIA_INDP_STATS_IPRAN_RAW.TRAN_BAD_PACKETS_PERIODIC IS 'Reescritura de la columna TRANSMITTED_BAD_PACKETS_PERIODIC';
COMMENT ON COLUMN ALC_MEDIA_INDP_STATS_IPRAN_RAW.MONITORED_OBJECT_SITE_ID IS 'TEXT(IP)';
COMMENT ON COLUMN ALC_MEDIA_INDP_STATS_IPRAN_RAW.MONITORED_OBJECT_SITENAME IS 'TEXT(EQUIPO)';
COMMENT ON COLUMN ALC_MEDIA_INDP_STATS_IPRAN_RAW.IN_BANDWITH_UTIL IS 'Calculada con la fórmula en tabla auxiliar --> 8*RECEIVED_OCTETS_PERIODIC/(OUTPUT_SPEED*900000)';
COMMENT ON COLUMN ALC_MEDIA_INDP_STATS_IPRAN_RAW.OUT_BANDWITH_UTIL IS 'Calculada con la fórmula en tabla auxiliar --> 8*TRANSMITTED_OCTETS_PERIODIC/(OUTPUT_SPEED*900000)';
COMMENT ON COLUMN ALC_MEDIA_INDP_STATS_IPRAN_RAW.REC_OCTETS IS 'Calculada con la fórmula en tabla auxiliar --> RECEIVED_OCTETS_PERIODIC/1048576	en (MB)';
COMMENT ON COLUMN ALC_MEDIA_INDP_STATS_IPRAN_RAW.TRANS_OCTETS IS 'Calculada con la fórmula en tabla auxiliar --> TRANSMITTED_OCTETS_PERIODIC/1048576	en (MB)';