--
-- TYPE
-- DROP TYPE ALC_S_C_S_IPRAN_ROW;

CREATE OR REPLACE TYPE ALC_S_C_S_IPRAN_ROW AS OBJECT(
  FECHA	                      DATE,
  SYSTEM_CPU_USAGE	          NUMBER,
  TIME_CAPTURED	              NUMBER,
  PERIODIC_TIME	              NUMBER,
  MONITORED_OBJECT_SITE_ID	  VARCHAR2(15 CHAR),
  MONITORED_OBJECT_SITE_NAME	VARCHAR2(50 CHAR)
);
-- DROP TYPE ALC_S_C_S_IPRAN_TY;
CREATE OR REPLACE TYPE ALC_S_C_S_IPRAN_TY IS TABLE OF ALC_S_C_S_IPRAN_ROW;
--
-- DROP TABLE ALC_SYSTEM_CPU_STATS_IPRAN_RAW;
--
CREATE TABLE ALC_SYSTEM_CPU_STATS_IPRAN_RAW(
  FECHA                       DATE NOT NULL,
  SYSTEM_CPU_USAGE	          NUMBER  DEFAULT 0 NOT NULL,
  TIME_CAPTURED	              NUMBER  DEFAULT 0 NOT NULL,
  PERIODIC_TIME	              NUMBER  DEFAULT 0 NOT NULL,
  MONITORED_OBJECT_SITE_ID    VARCHAR2(50 CHAR) NOT NULL,
  MONITORED_OBJECT_SITE_NAME  VARCHAR2(50 CHAR) NOT NULL
) NOCOMPRESS NOLOGGING;

COMMENT ON TABLE ALC_SYSTEM_CPU_STATS_IPRAN_RAW IS 'Medición: Medicion de la CPU';


--
--
--
INSERT INTO ALC_SYSTEM_CPU_STATS_IPRAN_RAW (FECHA                       ,
        SYSTEM_CPU_USAGE	          ,
        TIME_CAPTURED	              ,
        PERIODIC_TIME	              ,
        MONITORED_OBJECT_SITE_ID    ,
        MONITORED_OBJECT_SITE_NAME)
SELECT  FECHA                       ,
        SYSTEM_CPU_USAGE	          ,
        TIME_CAPTURED	              ,
        PERIODIC_TIME	              ,
        MONITORED_OBJECT_SITE_ID    ,
        MONITORED_OBJECT_SITE_NAME
FROM  XML_SYSTEM_STATS_3;        