--
-- Tabla auxiliar para almacenar la info del archivo YYYYMMDDHH24MI_mediaIndependStats.xml_1
--
-- DROP TABLE XML_MEDIA_INDEPEND_STATS_1 PURGE;

CREATE TABLE XML_MEDIA_INDEPEND_STATS_1 (
  DROP_EVENTS_PERIODIC	          NUMBER
  ,DROPPED_FRAMES_PERIODIC	      NUMBER
  ,RECEIVED_PACKETS_PERIODIC	    NUMBER
  ,TRANSMITTED_PACKETS_PERIODIC	  NUMBER
  ,RECEIVED_OCTETS_PERIODIC       NUMBER
  ,TRANSMITTED_OCTETS_PERIODIC    NUMBER
  ,REC_NON_UNI_PAC_PERIODIC	      NUMBER --RECEIVED_NON_UNICAST_PACKETS_PERIODIC
  ,TRANS_NON_UNI_PAC_PERIODIC     NUMBER --TRANSMITTED_NON_UNICAST_PACKETS_PERIODIC
  ,RECEIVED_BAD_PACKETS_PERIODIC	NUMBER
  ,TRANS_BAD_PAC_PERIODIC	        NUMBER --TRANSMITTED_BAD_PACKETS_PERIODIC
  ,INPUT_SPEED	                  NUMBER
  ,OUTPUT_SPEED	                  NUMBER
  ,DUPLEX	                        VARCHAR2(500 CHAR)
  ,DUPLEX_CHANGES_PERIODIC	      NUMBER
  ,TIME_CAPTURED	                NUMBER
  ,PERIODIC_TIME	                NUMBER
  ,MONITORED_OBJECT_POINTER	      VARCHAR2(500 CHAR)
  ,MONITORED_OBJECT_SITE_ID	      VARCHAR2(15 CHAR)
  ,MONITORED_OBJECT_SITE_NAME	    VARCHAR2(50 CHAR)
  ,IN_BANDWITH_UTIL               AS  (DECODE(OUTPUT_SPEED,0,0,8*RECEIVED_OCTETS_PERIODIC/(OUTPUT_SPEED*900000)))
  ,OUT_BANDWITH_UTIL              AS  (DECODE(OUTPUT_SPEED,0,0,8*TRANSMITTED_OCTETS_PERIODIC/(OUTPUT_SPEED*900000)))
  ,REC_OCTETS_MB                  AS  (RECEIVED_OCTETS_PERIODIC/1048576)
  ,TRANS_OCTETS_MB                AS  (TRANSMITTED_OCTETS_PERIODIC/1048576)
  ) NOCOMPRESS NOLOGGING;
  COMMENT ON TABLE XML_MEDIA_INDEPEND_STATS_1 IS 'Tabla auxiliar para almacenar la info del archivo YYYYMMDDHH24MI_mediaIndependStats.xml_1';
  COMMENT ON COLUMN XML_MEDIA_INDEPEND_STATS_1.REC_NON_UNI_PAC_PERIODIC IS 'Reescritura de la columna RECEIVED_NON_UNICAST_PACKETS_PERIODIC';
  COMMENT ON COLUMN XML_MEDIA_INDEPEND_STATS_1.TRANS_NON_UNI_PAC_PERIODIC IS 'Reescritura de la columna TRANSMITTED_NON_UNICAST_PACKETS_PERIODIC';
  COMMENT ON COLUMN XML_MEDIA_INDEPEND_STATS_1.TRANS_BAD_PAC_PERIODIC IS 'Reescritura de la columna TRANSMITTED_BAD_PACKETS_PERIODIC'