--
-- Tabla auxiliar para almacenar la info del archivo YYYYMMDDHH24MI_mediaIndependStats.xml
--  DROP TABLE XML_MEDIA_INDEPEND_STATS PURGE;

CREATE TABLE XML_MEDIA_INDEPEND_STATS (
    FECHA                         DATE GENERATED ALWAYS AS (TO_DATE(SUBSTR(NOMBRE_CSV,-33,2)||'.'||
                                                                          SUBSTR(NOMBRE_CSV,-35,2)||'.'||
                                                                          SUBSTR(NOMBRE_CSV,-39,4)||' '||
                                                                          SUBSTR(NOMBRE_CSV,-31,2)||':'||
                                                                          SUBSTR(NOMBRE_CSV,-29,2),'DD.MM.YYYY HH24:MI')) VIRTUAL
    ,SPECIFIC_TYPE	              VARCHAR2(50 CHAR)
    ,DESCRIPTION	                VARCHAR2(255 CHAR)
    ,MODO	                        VARCHAR2(50 CHAR) --MODE
    ,MAC_ADDRESS	                VARCHAR2(50 CHAR)
    ,MTU_VALUE	                  VARCHAR2(50 CHAR)
    ,SPEED	                      VARCHAR2(50 CHAR)
    ,ACTUAL_SPEED	                VARCHAR2(50 CHAR)
    ,NUMBER_OF_POSSIBLE_CHANNELS	NUMBER
    ,SITE_ID	                    VARCHAR2(50 CHAR)
    ,SITE_NAME	                  VARCHAR2(50 CHAR)
    ,OPERATIONAL_STATE	          VARCHAR2(50 CHAR)
    ,ADMINISTRATIVE_STATE	        VARCHAR2(50 CHAR)
    ,OLC_STATE	                  VARCHAR2(255 CHAR)
    ,OBJECT_FULL_NAME	            VARCHAR2(500 CHAR)
    ,MEDICION                     VARCHAR2(50 CHAR)
    ,NOMBRE_CSV                   VARCHAR2(100 CHAR)
) NOCOMPRESS NOLOGGING
PARTITION BY RANGE (FECHA)
(PARTITION MEDIAINDEPENDSTATS20161128 VALUES LESS THAN (TO_DATE('29.11.2016','DD.MM.YYYY')) TABLESPACE DEVELOPER PCTFREE 10 PCTUSED 80)
 TABLESPACE DEVELOPER;

COMMENT ON TABLE XML_MEDIA_INDEPEND_STATS IS 'Tabla auxiliar para almacenar la info del archivo YYYYMMDDHH24MI_mediaIndependStats.xml';
COMMENT ON COLUMN XML_MEDIA_INDEPEND_STATS.MODO IS 'Reescritura de la columna MODE por ser palabra reservada';

ALTER TABLE XML_MEDIA_INDEPEND_STATS ADD PARTITION MEDIAINDEPENDSTATS20161129 VALUES LESS THAN (TO_DATE('30.11.2016','DD.MM.YYYY')) TABLESPACE DEVELOPER PCTFREE 10 PCTUSED 80;
ALTER TABLE XML_MEDIA_INDEPEND_STATS ADD PARTITION MEDIAINDEPENDSTATS20161130 VALUES LESS THAN (TO_DATE('01.12.2016','DD.MM.YYYY')) TABLESPACE DEVELOPER PCTFREE 10 PCTUSED 80;
ALTER TABLE XML_MEDIA_INDEPEND_STATS ADD PARTITION MEDIAINDEPENDSTATS20161201 VALUES LESS THAN (TO_DATE('02.12.2016','DD.MM.YYYY')) TABLESPACE DEVELOPER PCTFREE 10 PCTUSED 80;
ALTER TABLE XML_MEDIA_INDEPEND_STATS ADD PARTITION MEDIAINDEPENDSTATS20161202 VALUES LESS THAN (TO_DATE('03.12.2016','DD.MM.YYYY')) TABLESPACE DEVELOPER PCTFREE 10 PCTUSED 80;
ALTER TABLE XML_MEDIA_INDEPEND_STATS ADD PARTITION MEDIAINDEPENDSTATS20161203 VALUES LESS THAN (TO_DATE('04.12.2016','DD.MM.YYYY')) TABLESPACE DEVELOPER PCTFREE 10 PCTUSED 80;
ALTER TABLE XML_MEDIA_INDEPEND_STATS ADD PARTITION MEDIAINDEPENDSTATS20161204 VALUES LESS THAN (TO_DATE('05.12.2016','DD.MM.YYYY')) TABLESPACE DEVELOPER PCTFREE 10 PCTUSED 80;
ALTER TABLE XML_MEDIA_INDEPEND_STATS ADD PARTITION MEDIAINDEPENDSTATS20161205 VALUES LESS THAN (TO_DATE('06.12.2016','DD.MM.YYYY')) TABLESPACE DEVELOPER PCTFREE 10 PCTUSED 80;
ALTER TABLE XML_MEDIA_INDEPEND_STATS ADD PARTITION MEDIAINDEPENDSTATS20161206 VALUES LESS THAN (TO_DATE('07.12.2016','DD.MM.YYYY')) TABLESPACE DEVELOPER PCTFREE 10 PCTUSED 80;
ALTER TABLE XML_MEDIA_INDEPEND_STATS ADD PARTITION MEDIAINDEPENDSTATS20161207 VALUES LESS THAN (TO_DATE('08.12.2016','DD.MM.YYYY')) TABLESPACE DEVELOPER PCTFREE 10 PCTUSED 80;
ALTER TABLE XML_MEDIA_INDEPEND_STATS ADD PARTITION MEDIAINDEPENDSTATS20161208 VALUES LESS THAN (TO_DATE('09.12.2016','DD.MM.YYYY')) TABLESPACE DEVELOPER PCTFREE 10 PCTUSED 80;
ALTER TABLE XML_MEDIA_INDEPEND_STATS ADD PARTITION MEDIAINDEPENDSTATS20161209 VALUES LESS THAN (TO_DATE('10.12.2016','DD.MM.YYYY')) TABLESPACE DEVELOPER PCTFREE 10 PCTUSED 80;
ALTER TABLE XML_MEDIA_INDEPEND_STATS ADD PARTITION MEDIAINDEPENDSTATS20161210 VALUES LESS THAN (TO_DATE('11.12.2016','DD.MM.YYYY')) TABLESPACE DEVELOPER PCTFREE 10 PCTUSED 80;
ALTER TABLE XML_MEDIA_INDEPEND_STATS ADD PARTITION MEDIAINDEPENDSTATS20161211 VALUES LESS THAN (TO_DATE('12.12.2016','DD.MM.YYYY')) TABLESPACE DEVELOPER PCTFREE 10 PCTUSED 80;
ALTER TABLE XML_MEDIA_INDEPEND_STATS ADD PARTITION MEDIAINDEPENDSTATS20161212 VALUES LESS THAN (TO_DATE('13.12.2016','DD.MM.YYYY')) TABLESPACE DEVELOPER PCTFREE 10 PCTUSED 80;
ALTER TABLE XML_MEDIA_INDEPEND_STATS ADD PARTITION MEDIAINDEPENDSTATS20161213 VALUES LESS THAN (TO_DATE('14.12.2016','DD.MM.YYYY')) TABLESPACE DEVELOPER PCTFREE 10 PCTUSED 80;
ALTER TABLE XML_MEDIA_INDEPEND_STATS ADD PARTITION MEDIAINDEPENDSTATS20161214 VALUES LESS THAN (TO_DATE('15.12.2016','DD.MM.YYYY')) TABLESPACE DEVELOPER PCTFREE 10 PCTUSED 80;
ALTER TABLE XML_MEDIA_INDEPEND_STATS ADD PARTITION MEDIAINDEPENDSTATS20161215 VALUES LESS THAN (TO_DATE('16.12.2016','DD.MM.YYYY')) TABLESPACE DEVELOPER PCTFREE 10 PCTUSED 80;
ALTER TABLE XML_MEDIA_INDEPEND_STATS ADD PARTITION MEDIAINDEPENDSTATS20161216 VALUES LESS THAN (TO_DATE('17.12.2016','DD.MM.YYYY')) TABLESPACE DEVELOPER PCTFREE 10 PCTUSED 80;
ALTER TABLE XML_MEDIA_INDEPEND_STATS ADD PARTITION MEDIAINDEPENDSTATS20161217 VALUES LESS THAN (TO_DATE('18.12.2016','DD.MM.YYYY')) TABLESPACE DEVELOPER PCTFREE 10 PCTUSED 80;
ALTER TABLE XML_MEDIA_INDEPEND_STATS ADD PARTITION MEDIAINDEPENDSTATS20161218 VALUES LESS THAN (TO_DATE('19.12.2016','DD.MM.YYYY')) TABLESPACE DEVELOPER PCTFREE 10 PCTUSED 80;
ALTER TABLE XML_MEDIA_INDEPEND_STATS ADD PARTITION MEDIAINDEPENDSTATS20161219 VALUES LESS THAN (TO_DATE('20.12.2016','DD.MM.YYYY')) TABLESPACE DEVELOPER PCTFREE 10 PCTUSED 80;
ALTER TABLE XML_MEDIA_INDEPEND_STATS ADD PARTITION MEDIAINDEPENDSTATS20161220 VALUES LESS THAN (TO_DATE('21.12.2016','DD.MM.YYYY')) TABLESPACE DEVELOPER PCTFREE 10 PCTUSED 80;
ALTER TABLE XML_MEDIA_INDEPEND_STATS ADD PARTITION MEDIAINDEPENDSTATS20161221 VALUES LESS THAN (TO_DATE('22.12.2016','DD.MM.YYYY')) TABLESPACE DEVELOPER PCTFREE 10 PCTUSED 80;
ALTER TABLE XML_MEDIA_INDEPEND_STATS ADD PARTITION MEDIAINDEPENDSTATS20161222 VALUES LESS THAN (TO_DATE('23.12.2016','DD.MM.YYYY')) TABLESPACE DEVELOPER PCTFREE 10 PCTUSED 80;
ALTER TABLE XML_MEDIA_INDEPEND_STATS ADD PARTITION MEDIAINDEPENDSTATS20161223 VALUES LESS THAN (TO_DATE('24.12.2016','DD.MM.YYYY')) TABLESPACE DEVELOPER PCTFREE 10 PCTUSED 80;
ALTER TABLE XML_MEDIA_INDEPEND_STATS ADD PARTITION MEDIAINDEPENDSTATS20161224 VALUES LESS THAN (TO_DATE('25.12.2016','DD.MM.YYYY')) TABLESPACE DEVELOPER PCTFREE 10 PCTUSED 80;
ALTER TABLE XML_MEDIA_INDEPEND_STATS ADD PARTITION MEDIAINDEPENDSTATS20161225 VALUES LESS THAN (TO_DATE('26.12.2016','DD.MM.YYYY')) TABLESPACE DEVELOPER PCTFREE 10 PCTUSED 80;
ALTER TABLE XML_MEDIA_INDEPEND_STATS ADD PARTITION MEDIAINDEPENDSTATS20161226 VALUES LESS THAN (TO_DATE('27.12.2016','DD.MM.YYYY')) TABLESPACE DEVELOPER PCTFREE 10 PCTUSED 80;
ALTER TABLE XML_MEDIA_INDEPEND_STATS ADD PARTITION MEDIAINDEPENDSTATS20161227 VALUES LESS THAN (TO_DATE('28.12.2016','DD.MM.YYYY')) TABLESPACE DEVELOPER PCTFREE 10 PCTUSED 80;
ALTER TABLE XML_MEDIA_INDEPEND_STATS ADD PARTITION MEDIAINDEPENDSTATS20161228 VALUES LESS THAN (TO_DATE('29.12.2016','DD.MM.YYYY')) TABLESPACE DEVELOPER PCTFREE 10 PCTUSED 80;
ALTER TABLE XML_MEDIA_INDEPEND_STATS ADD PARTITION MEDIAINDEPENDSTATS20161229 VALUES LESS THAN (TO_DATE('30.12.2016','DD.MM.YYYY')) TABLESPACE DEVELOPER PCTFREE 10 PCTUSED 80;
ALTER TABLE XML_MEDIA_INDEPEND_STATS ADD PARTITION MEDIAINDEPENDSTATS20161230 VALUES LESS THAN (TO_DATE('31.12.2016','DD.MM.YYYY')) TABLESPACE DEVELOPER PCTFREE 10 PCTUSED 80;
ALTER TABLE XML_MEDIA_INDEPEND_STATS ADD PARTITION MEDIAINDEPENDSTATS20161231 VALUES LESS THAN (TO_DATE('01.01.2017','DD.MM.YYYY')) TABLESPACE DEVELOPER PCTFREE 10 PCTUSED 80;

