--
-- Tabla auxiliar para almacenar la info del archivo YYYYMMDDHH24MI_SystemStats.xml_2
--
CREATE TABLE XML_SYSTEM_STATS_2 (
  ALLOCATED_MEMORY	          NUMBER
  ,TIME_CAPTURED	            NUMBER
  ,PERIODIC_TIME	            NUMBER
  ,MONITORED_OBJECT_SITE_ID	  VARCHAR2(15 CHAR)
  ,MONITORED_OBJECT_SITE_NAME	VARCHAR2(50 CHAR)
  ,ALLOCATED_MEMORY_MB        AS (ALLOCATED_MEMORY/1048576)
);

COMMENT ON TABLE XML_SYSTEM_STATS_2 IS 'Tabla auxiliar para almacenar la info del archivo YYYYMMDDHH24MI_SystemStats.xml_2';