--
-- Tabla auxiliar para almacenar la info del archivo YYYYMMDDHH24MI_SystemStats.xml_1
--
CREATE TABLE XML_SYSTEM_STATS_1 (
  AVAILABLE_MEMORY	          NUMBER
  ,TIME_CAPTURED            	NUMBER
  ,PERIODIC_TIME	            NUMBER
  ,MONITORED_OBJECT_SITE_ID	  VARCHAR2(15 CHAR)
  ,MONITORED_OBJECT_SITE_NAME	VARCHAR2(50 CHAR)
--  ,AVAILABLE_MEMORY_PCT       AS (AVAILABLE_MEMORY/(AVAILABLE_MEMORY+ALLOCATED_MEMORY))
  ,AVAILABLE_MEMORY_MB        AS (AVAILABLE_MEMORY/1048576)
);

COMMENT ON TABLE XML_SYSTEM_STATS_1 IS 'Tabla auxiliar para almacenar la info del archivo YYYYMMDDHH24MI_SystemStats.xml_1';